<?php
declare(strict_types=1);

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

$rootpath = './../';
$thispath = './';
require_once $rootpath . 'global.php';
require_once INC_PATH . '/readconfig.php';
require_once INC_PATH . '/functions_mkprettytime.php';
require TSDIR . '/cache/freeleech.php';

if ($usergroups['cansettingspanel'] !== '1') {
    stdhead();
    error_no_permission(true);
    exit();
}

function flash_message(?string $message = null, string $type = 'info'): void
{
    if ($message !== null) {
        $_SESSION['flash'][] = ['message' => $message, 'type' => $type];
        return;
    }
    if (empty($_SESSION['flash'])) return;

    echo '<div aria-live="polite" aria-atomic="true" class="position-relative">
          <div class="toast-container position-fixed top-0 end-0 p-3" style="z-index:1100">';
    foreach ($_SESSION['flash'] as $flash) {
        $cls = match($flash['type']) {
            'success'        => 'bg-success text-white',
            'error','danger' => 'bg-danger text-white',
            'warning'        => 'bg-warning text-dark',
            default          => 'bg-info text-white',
        };
        $msg = htmlspecialchars($flash['message']);
        echo "<div class='toast border-0 mb-2' role='alert' aria-live='assertive' aria-atomic='true'>
                <div class='toast-header {$cls}'>
                  <strong class='me-auto'>Message</strong><small>Now</small>
                  <button type='button' class='btn-close' data-bs-dismiss='toast'></button>
                </div>
                <div class='toast-body'>{$msg}</div>
              </div>";
    }
    echo '</div></div>
    <script>document.addEventListener("DOMContentLoaded",()=>{
      document.querySelectorAll(".toast").forEach(t=>new bootstrap.Toast(t,{delay:5000}).show());
    });</script>';
    unset($_SESSION['flash']);
}

function admin_redirect(string $url): never
{
    if (!headers_sent()) {
        header("Location: " . str_replace("&amp;", "&", $url));
    } else {
        echo "<meta http-equiv='refresh' content='0; url={$url}'>";
    }
    exit;
}

function rebuild_announce_settings(): bool
{
    global $cache, $db;
    $announce = $cache->read('ANNOUNCE');
    if (!is_array($announce)) return false;

    $kps            = $cache->read('KPS') ?? [];
    $bonus          = $kps['bonus']          ?? 'enable';
    $kpsseed        = $kps['kpsseed']        ?? '5.0';
    $bdayreward     = $kps['bdayreward']     ?? 'yes';
    $bdayrewardtype = $kps['bdayrewardtype'] ?? 'silverleech';

    $settings = [];
    $q = $db->simple_select("settings", "name, value");
    while ($r = $db->fetch_array($q)) $settings[$r['name']] = $r['value'];

    $keys = ['announce_actions','aggressivecheat','nc','announce_wait','announce_interval',
             'max_rate','bannedclientdetect','allowed_clients','detectbrowsercheats',
             'checkconnectable','checkip','mysql_host','mysql_user','mysql_pass','mysql_db'];

    $c  = "<?php #DO NOT EDIT THIS FILE, PLEASE USE THE SETTINGS PANEL!!\n";
    $c .= "if(!defined('IN_ANNOUNCE')) die('Hacking attempt!');\n\n";
    foreach ($keys as $k) $c .= "\${$k} = '" . addslashes((string)($announce[$k] ?? '')) . "';\n";
    foreach ([
        'BASEURL'=>$settings['BASEURL']??'','SITENAME'=>$settings['SITENAME']??'',
        'privatetrackerpatch'=>$settings['privatetrackerpatch']??'no',
        'gzipcompress'=>$settings['gzipcompress']??'yes',
        'charset'=>$settings['charset']??'UTF-8',
        'aggressivecheckip'=>$settings['aggressivecheckip']??'no',
        'snatchmod'=>$settings['snatchmod']??'yes',
        'bonus'=>$bonus,'kpsseed'=>$kpsseed,'bdayreward'=>$bdayreward,'bdayrewardtype'=>$bdayrewardtype,
    ] as $k => $v) $c .= "\${$k} = '" . addslashes((string)$v) . "';\n";
    $c .= "?>";
    return file_put_contents(INC_PATH . '/config_announce.php', $c) !== false;
}

// ── Load settings ──────────────────────────────────────────────────────────────
$settings = [];
$q = $db->simple_select("settings", "name, value");
while ($r = $db->fetch_array($q)) $settings[$r['name']] = $r['value'];
$announce_url = $settings['announce_urls[]'] ?? '';

ob_start();

// ── POST handlers ──────────────────────────────────────────────────────────────
match(true) {

    isset($_POST['save_kps']) => (function() use ($cache): void {
        $keys = ['bonus','kpsseed','kpsupload','kpscomment','kpsthanks','kpsrate','kpspoll',
                 'kpsmaxpoint','kpsinvite','kpstitle','kpsvip','kpsgift','kpswarning','kpsratiofix',
                 'bdayreward','bdayrewardtype'];
        $data = array_intersect_key($_POST['configoption'] ?? [], array_flip($keys));
        if (!empty($data)) $cache->update('KPS', $data);
        flash_message("KPS settings saved successfully!", "success");
        admin_redirect("settings.php#kps-settings");
    })(),

    isset($_POST['save_user_management']) => (function() use ($cache): void {
        $keys = ['ai','autoinvitetime','max_dead_torrent_time','promote_gig_limit','promote_min_ratio',
                 'promote_min_reg_days','demote_min_ratio','referrergift','leechwarn_min_ratio',
                 'leechwarn_gig_limit','leechwarn_length','leechwarn_remove_ratio','ban_user_limit'];
        $data = array_intersect_key($_POST['configoption'] ?? [], array_flip($keys));
        if (!empty($data)) $cache->update('CLEANUP', $data);
        flash_message("Cleanup settings saved successfully!", "success");
        admin_redirect("settings.php?saved=cleanup#user-management-settings");
    })(),

    isset($_POST['save_registration']) => (function() use ($cache): void {
        $keys = ['invitesystem','regtype','minnamelength','maxnamelength','maxip','illegalusernames',
                 'minpasswordlength','maxpasswordlength','requirecomplexpasswords','failedlogincount',
                 'failedlogintext','username_method','disableregs','r_verification','maxusers',
                 'coppa','_d_usergroup','invite_count','autogigsignup','autosbsignup'];
        $data = array_intersect_key($_POST['configoption'] ?? [], array_flip($keys));
        if (!empty($data)) $cache->update('SIGNUP', $data);
        flash_message("Registration settings saved successfully!", "success");
        admin_redirect("settings.php?saved=registration#registration-settings");
    })(),

    isset($_POST['save_announce']) => (function() use ($cache): void {
        $keys = ['announce_actions','aggressivecheat','nc','announce_wait','announce_interval',
                 'max_rate','bannedclientdetect','allowed_clients','detectbrowsercheats',
                 'checkconnectable','checkip','mysql_host','mysql_user','mysql_pass','mysql_db'];
        $data = array_intersect_key($_POST['configoption'] ?? [], array_flip($keys));
        if (!empty($data)) { $cache->update('ANNOUNCE', $data); rebuild_announce_settings(); }
        flash_message("Announce settings saved successfully!", "success");
        admin_redirect("settings.php?saved=announce#announce-settings");
    })(),

    isset($_POST['save_freeleech']) => (function(): void {
        $start   = $_POST['configoption']['start']  ?? '';
        $end     = $_POST['configoption']['end']    ?? '';
        $flstype = $_POST['configoption']['system'] ?? 'freeleech';
        $file    = TSDIR . '/cache/freeleech.php';
        $fp      = @fopen($file, 'w');
        if ($fp) {
            $c  = "<?php\n/** Cache: FreeLeech | Generated: " . gmdate('r') . " */\n";
            $c .= "\$__FLSTYPE = '" . addslashes($flstype) . "';\n";
            $c .= "\$__F_START = '" . addslashes($start) . "';\n";
            $c .= "\$__F_END   = '" . addslashes($end) . "';\n?>";
            fwrite($fp, $c); fclose($fp);
            flash_message("Freeleech settings saved successfully!", "success");
            admin_redirect("settings.php?saved=freeleech#freeleech-settings");
        }
        flash_message("Error: unable to write FreeLeech cache!", "danger");
        admin_redirect("settings.php#freeleech-settings");
    })(),

    isset($_POST['save_staff']) => (function() use ($db): void {
        $valid = [];
        $q = $db->sql_query("SELECT u.id, u.username FROM users u LEFT JOIN usergroups g ON u.usergroup=g.gid WHERE u.enabled='yes' AND (g.cansettingspanel='1' OR g.issupermod='1' OR g.canstaffpanel='1')");
        while ($r = $db->fetch_array($q)) $valid[(string)$r['id']] = $r['username'];

        $entries = []; $errors = [];
        foreach (($_POST['staffids'] ?? []) as $i => $rawId) {
            $id   = trim((string)$rawId);
            $name = trim((string)($_POST['staffnames'][$i] ?? ''));
            if ($id === '' && $name === '') continue;
            if ($id !== '' && !ctype_digit($id))      { $errors[] = "{$name}:{$id} (invalid ID format)"; continue; }
            if (!isset($valid[$id]))                   { $errors[] = "{$name}:{$id} (not allowed)"; continue; }
            if (strcasecmp($valid[$id], $name) !== 0) { $errors[] = "{$name}:{$id} (name does not match)"; continue; }
            $entries[] = "{$name}:{$id}";
        }
        if (!empty($errors)) {
            flash_message("Errors: " . implode(', ', $errors), "danger");
        } elseif (file_put_contents(CONFIG_DIR . '/STAFFTEAM', implode(',', $entries), LOCK_EX) === false) {
            flash_message("Failed to write STAFFTEAM config file!", "danger");
        } else {
            flash_message("Staff team saved successfully!", "success");
        }
        admin_redirect("settings.php#staff-team");
    })(),

    $_SERVER['REQUEST_METHOD'] === 'POST' => (function() use ($db, $settings): void {
        $opts   = $_POST['configoption'] ?? [];
        $ofType = $_POST['offline_mode_type'] ?? 'limited';
        $ofMins = (int)($_POST['offline_minutes_input'] ?? 30);

        if (($opts['SITEONLINE'] ?? '') === 'no') {
            if ($ofType === 'unlimited') {
                $opts['offline_minutes'] = 'unlimited';
                write_log("[MAINTENANCE] Site set to offline (unlimited)");
            } else {
                $ofMins = max(1, min(1440, $ofMins));
                $end    = time() + $ofMins * 60;
                $opts['offline_minutes'] = $end;
                write_log("[MAINTENANCE] Site offline for {$ofMins}min, back at: " . date('Y-m-d H:i:s', $end));
                if ($end <= time()) { $opts['SITEONLINE'] = 'yes'; $opts['offline_minutes'] = ''; }
            }
        } else {
            $opts['offline_minutes'] = '';
            if (isset($opts['SITEONLINE'])) write_log("[MAINTENANCE] Site set to online");
        }

        $db->sql_query("START TRANSACTION");
        try {
            foreach ($opts as $name => $value) {
                if (!$db->sql_query("UPDATE settings SET value=" . $db->sqlesc($value) . " WHERE name=" . $db->sqlesc($name)))
                    throw new \Exception("Failed to update '{$name}'");
            }
            $db->sql_query("COMMIT");
            rebuild_settings();
            flash_message("Settings updated successfully!", "success");
        } catch (\Throwable $e) {
            $db->sql_query("ROLLBACK");
            write_log("[ERROR] " . $e->getMessage());
            flash_message("Error: " . $e->getMessage(), "danger");
        }
        admin_redirect($_SERVER['PHP_SELF']);
    })(),

    default => null,
};

ob_end_flush();

// ── Load caches ────────────────────────────────────────────────────────────────
$announce = $cache->read('ANNOUNCE') ?? [];
foreach (['announce_actions','aggressivecheat','nc','announce_wait','announce_interval',
          'max_rate','bannedclientdetect','allowed_clients','detectbrowsercheats',
          'checkconnectable','checkip','mysql_host','mysql_user','mysql_pass','mysql_db'] as $k) $$k = $announce[$k] ?? '';

$kps            = $cache->read('KPS') ?? [];
$bonus          = $kps['bonus']          ?? 'enable';
$kpsseed        = $kps['kpsseed']        ?? '5.0';
$kpsupload      = $kps['kpsupload']      ?? '0';
$kpscomment     = $kps['kpscomment']     ?? '0';
$kpsthanks      = $kps['kpsthanks']      ?? '0';
$kpsrate        = $kps['kpsrate']        ?? '0';
$kpspoll        = $kps['kpspoll']        ?? '0';
$kpsmaxpoint    = $kps['kpsmaxpoint']    ?? '0';
$kpsinvite      = $kps['kpsinvite']      ?? 'yes';
$kpstitle       = $kps['kpstitle']       ?? 'yes';
$kpsvip         = $kps['kpsvip']         ?? 'yes';
$kpsgift        = $kps['kpsgift']        ?? 'yes';
$kpswarning     = $kps['kpswarning']     ?? 'yes';
$kpsratiofix    = $kps['kpsratiofix']    ?? 'yes';
$bdayreward     = $kps['bdayreward']     ?? 'yes';
$bdayrewardtype = $kps['bdayrewardtype'] ?? 'silverleech';

$signup               = $cache->read('SIGNUP') ?? [];
$invitesystem         = $signup['invitesystem']           ?? 'on';
$regtype              = $signup['regtype']                ?? 'instant';
$minnamelength        = $signup['minnamelength']          ?? '3';
$maxnamelength        = $signup['maxnamelength']          ?? '20';
$maxip                = $signup['maxip']                  ?? '0';
$illegalusernames     = $signup['illegalusernames']       ?? '';
$minpasswordlength    = $signup['minpasswordlength']      ?? '6';
$maxpasswordlength    = $signup['maxpasswordlength']      ?? '40';
$requirecomplexpasswords = $signup['requirecomplexpasswords'] ?? '0';
$failedlogincount     = $signup['failedlogincount']       ?? '0';
$failedlogintext      = $signup['failedlogintext']        ?? '0';
$username_method      = $signup['username_method']        ?? '0';
$disableregs          = $signup['disableregs']            ?? '0';
$r_verification       = $signup['r_verification']         ?? 'yes';
$maxusers             = $signup['maxusers']               ?? '0';
$coppa                = $signup['coppa']                  ?? 'disabled';
$_d_usergroup         = $signup['_d_usergroup']           ?? '1';
$invite_count         = $signup['invite_count']           ?? '0';
$autogigsignup        = $signup['autogigsignup']          ?? '0';
$autosbsignup         = $signup['autosbsignup']           ?? '0';

$cleanup              = $cache->read('CLEANUP') ?? [];
$ai                   = $cleanup['ai']                    ?? 'no';
$autoinvitetime       = $cleanup['autoinvitetime']        ?? '30';
$max_dead_torrent_time= $cleanup['max_dead_torrent_time'] ?? '30';
$promote_gig_limit    = $cleanup['promote_gig_limit']     ?? '0';
$promote_min_ratio    = $cleanup['promote_min_ratio']     ?? '0.5';
$promote_min_reg_days = $cleanup['promote_min_reg_days']  ?? '30';
$demote_min_ratio     = $cleanup['demote_min_ratio']      ?? '0.2';
$referrergift         = $cleanup['referrergift']          ?? '0';
$leechwarn_min_ratio  = $cleanup['leechwarn_min_ratio']   ?? '0.3';
$leechwarn_gig_limit  = $cleanup['leechwarn_gig_limit']   ?? '10';
$leechwarn_length     = $cleanup['leechwarn_length']      ?? '2';
$leechwarn_remove_ratio = $cleanup['leechwarn_remove_ratio'] ?? '0.5';
$ban_user_limit       = $cleanup['ban_user_limit']        ?? '3';

$offlineMinutesValue = $settings['offline_minutes'] ?? '';
$isUnlimited         = ($settings['SITEONLINE'] ?? 'yes') === 'no' && $offlineMinutesValue === 'unlimited';
$durationMinutes     = 30;
$timeRemaining       = '';
if (($settings['SITEONLINE'] ?? 'yes') === 'no') {
    if ($isUnlimited) {
        $timeRemaining = '<span class="text-success">Unlimited (manual enable required)</span>';
    } elseif (is_numeric($offlineMinutesValue) && (int)$offlineMinutesValue > time()) {
        $rem             = (int)ceil(((int)$offlineMinutesValue - time()) / 60);
        $h               = (int)floor($rem / 60); $m = $rem % 60;
        $durationMinutes = max(1, $rem);
        $timeRemaining   = '<span class="text-warning">' . ($h > 0 ? "{$h}h " : '') . "{$m}m remaining</span>";
    } else {
        $durationMinutes = is_numeric($offlineMinutesValue) ? max(1, (int)$offlineMinutesValue) : 30;
        $timeRemaining   = '<span class="text-danger">Time expired (should auto-enable)</span>';
    }
}

$iv                  = $settings['iv']               ?? 'no';
$vkeyword            = $settings['vkeyword']         ?? 'no';
$reCAPTCHAPublickey  = $settings['reCAPTCHAPublickey']  ?? '';
$reCAPTCHAPrivatekey = $settings['reCAPTCHAPrivatekey'] ?? '';
$reCAPTCHATheme      = $settings['reCAPTCHATheme']      ?? 'white';
$reCAPTCHALanguage   = $settings['reCAPTCHALanguage']   ?? 'en';

$staffarray = [];
$staffFile  = CONFIG_DIR . '/STAFFTEAM';
if (is_readable($staffFile)) {
    foreach (explode(',', (string)file_get_contents($staffFile)) as $entry) {
        $parts = explode(':', trim($entry), 2);
        if (count($parts) === 2 && $parts[0] !== '') {
            $staffarray[] = ['name' => trim($parts[0]), 'id' => trim($parts[1])];
        }
    }
}
$availableStaff = [];
$q = $db->sql_query("SELECT u.id, u.username, g.title FROM users u LEFT JOIN usergroups g ON u.usergroup=g.gid WHERE u.enabled='yes' AND (g.cansettingspanel='1' OR g.issupermod='1' OR g.canstaffpanel='1') ORDER BY u.username ASC");
while ($r = $db->fetch_array($q)) $availableStaff[] = $r;

echo '<link href="'.$BASEURL.'/include/templates/default/style/bootstrap-icons.css" rel="stylesheet">';
echo '<link href="'.$BASEURL.'/include/templates/default/style/errorss.css" rel="stylesheet">';

stdhead();
flash_message();
?>
<title>Ruff Tracker Admin Panel</title>

<style>
/* ========== GLOBAL FONT SCALE ========== */
html {
    font-size: 120%;
}

/* ===== BASE ===== */
body {
    line-height: 1.6;
}

/* ===== SIDEBAR ===== */
.sidebar {
  background: #ffffff;
  border-right: 1px solid #e2e8f0;
  min-height: 100vh;
  position: sticky;
  top: 0;
  height: 100vh;
  overflow-y: auto;
  scrollbar-width: thin;
  padding-top: 8px;
}

.sidebar .nav-link {
  font-size: 16px;
  padding: 12px 18px;
  color: #475569;
  border-radius: 6px;
  margin: 2px 8px;
  border-left: 3px solid transparent;
  transition: all .15s;
}

.sidebar .nav-link i {
  font-size: 18px;
  width: 22px;
  text-align: center;
}

.sidebar .nav-link:hover {
  background: #eff6ff;
  color: #0d6efd;
  border-left-color: rgba(13,110,253,.25);
}

.sidebar .nav-link.active {
  background: #dbeafe;
  color: #0d6efd;
  border-left-color: #0d6efd;
  font-weight: 600;
}

/* ===== TOP BAR ===== */
.page-topbar {
  background: #fff;
  border-bottom: 1px solid #e2e8f0;
  padding: 15px 28px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  position: sticky;
  top: 0;
  z-index: 100;
  box-shadow: 0 1px 3px rgba(0,0,0,.06);
}

h1.h2 {
    font-size: 28px;
    font-weight: 700;
}

/* ===== CARD ===== */
.card {
  border: 1px solid #e2e8f0;
  border-radius: 10px;
  box-shadow: 0 1px 3px rgba(0,0,0,.04);
  background: #fff;
}

.card-header {
  background: #f8fafc;
  border-bottom: 1px solid #e2e8f0;
  font-weight: 600;
  color: #374151;
  font-size: 17px;
  padding: 16px 20px;
}

.card-header h5 {
  margin: 0;
  font-size: 17px;
}

.card-body {
    font-size: 16px;
    padding: 24px;
}

/* ===== FORM ===== */
.form-label {
    font-size: 15px;
    font-weight: 600;
}

.form-control, .form-select {
  font-size: 16px;
  padding: 12px 14px;
  border-color: #d1d5db;
  border-radius: 6px;
  background: #fafbfc;
  color: #1e293b;
  transition: border-color .15s, box-shadow .15s;
}

.form-control:focus, .form-select:focus {
  border-color: #0d6efd;
  box-shadow: 0 0 0 3px rgba(13,110,253,.12);
  background: #fff;
}

textarea.form-control {
  resize: vertical;
  min-height: 100px;
}

/* ===== INPUT GROUP ===== */
.input-group-text {
  font-size: 15px;
  padding: 12px 14px;
  background: #f1f5f9;
  border-color: #d1d5db;
  color: #64748b;
}

.help-icon {
  background: #eff6ff;
  border-color: #bfdbfe;
  color: #0d6efd;
  cursor: help;
}

.help-icon:hover {
  background: #dbeafe;
}

/* ===== BUTTONS ===== */
.btn {
    font-size: 16px;
    padding: 10px 20px;
    font-weight: 500;
}

.btn-primary {
  background: #0d6efd;
  border-color: #0d6efd;
  font-weight: 600;
  transition: background .15s, box-shadow .15s, transform .1s;
}

.btn-primary:hover {
  background: #0b5ed7;
  box-shadow: 0 4px 12px rgba(13,110,253,.3);
}

.btn-primary:active {
  transform: scale(.97);
}

/* ===== TABS ===== */
.nav-tabs .nav-link {
    font-size: 16px;
    padding: 10px 18px;
}

.tab-content {
    font-size: 16px;
}

.tab-content > .tab-pane {
  animation: fadeSlide .2s ease;
}

@keyframes fadeSlide {
  from { opacity:0; transform:translateY(5px); }
  to { opacity:1; transform:translateY(0); }
}

/* ===== TABLE ===== */
.table {
    font-size: 15px;
}

.table thead th {
    font-size: 14px;
    color: #64748b;
    border-bottom-width: 1px;
}

.table td, .table th {
    padding: 12px;
    vertical-align: middle;
}

.table-hover tbody tr:hover td {
    background: #f0f7ff;
}

.table-striped > tbody > tr:nth-of-type(odd) > * {
    background-color: rgba(0,0,0,.02);
}

/* ===== TEXT ===== */
.text-muted, small {
    font-size: 14px;
}

/* ===== ALERT ===== */
.alert {
    font-size: 15px;
    padding: 12px 16px;
}

/* ===== DROPDOWN ===== */
.dropdown-menu {
    font-size: 15px;
}

.dropdown-item {
    font-size: 15px;
    padding: 8px 16px;
}

/* ===== MISC ===== */
.section-sub {
  font-size: 14px;
  color: #64748b;
  border-bottom: 1px solid #e9ecef;
  display: flex;
  align-items: center;
  gap: 7px;
}

.section-sub::before {
  content: '';
  width: 3px;
  height: 11px;
  background: #0d6efd;
  border-radius: 2px;
}

.offline-wrap {
  background: #fff5f5;
  border: 1px solid #fecaca;
  border-radius: 8px;
  padding: 16px 20px;
  margin-top: 12px;
  font-size: 15px;
}
















/* ========== DARK MODE (Bootstrap compatible) ========== */

[data-bs-theme="dark"] {
    background: #0f172a;
    color: #e2e8f0;
}

/* SIDEBAR */
[data-bs-theme="dark"] .sidebar {
    background: #020617;
    border-right: 1px solid #1e293b;
}

[data-bs-theme="dark"] .sidebar .nav-link {
    color: #94a3b8;
}

[data-bs-theme="dark"] .sidebar .nav-link:hover {
    background: #1e293b;
    color: #60a5fa;
}

[data-bs-theme="dark"] .sidebar .nav-link.active {
    background: #1e293b;
    color: #60a5fa;
    border-left-color: #60a5fa;
}

/* TOPBAR */
[data-bs-theme="dark"] .page-topbar {
    background: #020617;
    border-bottom: 1px solid #1e293b;
}

/* CARD */
[data-bs-theme="dark"] .card {
    background: #020617;
    border: 1px solid #1e293b;
}

[data-bs-theme="dark"] .card-header {
    background: #020617;
    border-bottom: 1px solid #1e293b;
    color: #e2e8f0;
}

/* FORM */
[data-bs-theme="dark"] .form-control,
[data-bs-theme="dark"] .form-select {
    background: #020617;
    border-color: #1e293b;
    color: #e2e8f0;
}

[data-bs-theme="dark"] .form-control:focus,
[data-bs-theme="dark"] .form-select:focus {
    border-color: #3b82f6;
}

/* INPUT GROUP */
[data-bs-theme="dark"] .input-group-text {
    background: #020617;
    border-color: #1e293b;
    color: #94a3b8;
}

/* TABLE */
[data-bs-theme="dark"] .table {
    color: #e2e8f0;
}

[data-bs-theme="dark"] .table thead th {
    color: #94a3b8;
}

[data-bs-theme="dark"] .table-hover tbody tr:hover td {
    background: #1e293b;
}

[data-bs-theme="dark"] .table-striped > tbody > tr:nth-of-type(odd) > * {
    background-color: rgba(255,255,255,.03);
}

/* DROPDOWN */
[data-bs-theme="dark"] .dropdown-menu {
    background: #020617;
    border: 1px solid #1e293b;
}

[data-bs-theme="dark"] .dropdown-item {
    color: #e2e8f0;
}

[data-bs-theme="dark"] .dropdown-item:hover {
    background: #1e293b;
}

/* TEXT */
[data-bs-theme="dark"] .text-muted {
    color: #94a3b8 !important;
}

/* ALERT */
[data-bs-theme="dark"] .alert {
    background: #1e293b;
    border-color: #334155;
    color: #e2e8f0;
}
</style>

<div class="container mt-3">
<div class="row g-0">

  <!-- ══════════════════ SIDEBAR (оригинальный твой) ══════════════════════ -->
  <div class="col-md-3 col-lg-2 sidebar">
    <ul class="nav flex-column">
      <li class="nav-item"><a class="nav-link active" href="#main-settings" data-bs-toggle="tab"><i class="fas fa-cog me-2"></i>Main Settings</a></li>
      <li class="nav-item"><a class="nav-link" href="#tracker-settings" data-bs-toggle="tab"><i class="fas fa-server me-2"></i>Tracker Settings</a></li>
      <li class="nav-item"><a class="nav-link" href="#date-time" data-bs-toggle="tab"><i class="far fa-clock me-2"></i>Date & Time</a></li>
      <li class="nav-item"><a class="nav-link" href="#cookie-settings" data-bs-toggle="tab"><i class="fas fa-cookie me-2"></i>Cookie Settings</a></li>
      <li class="nav-item"><a class="nav-link" href="#avatar-settings" data-bs-toggle="tab"><i class="fas fa-user-circle me-2"></i>Avatar Settings</a></li>
      <li class="nav-item"><a class="nav-link" href="#security-settings" data-bs-toggle="tab"><i class="fas fa-shield-alt me-2"></i>Security Settings</a></li>
      <li class="nav-item"><a class="nav-link" href="#email-settings" data-bs-toggle="tab"><i class="fas fa-envelope me-2"></i>Email Settings</a></li>
      <li class="nav-item"><a class="nav-link" href="#announce-settings" data-bs-toggle="tab"><i class="fas fa-broadcast-tower me-2"></i>ANNOUNCE Settings</a></li>
      <li class="nav-item"><a class="nav-link" href="#kps-settings" data-bs-toggle="tab"><i class="fas fa-coins me-2"></i>KPS Settings</a></li>
      <li class="nav-item"><a class="nav-link" href="#user-management-settings" data-bs-toggle="tab"><i class="fas fa-users-cog me-2"></i>Cleanup Settings</a></li>
      <li class="nav-item"><a class="nav-link" href="#registration-settings" data-bs-toggle="tab"><i class="fas fa-user-plus me-2"></i>Registration</a></li>
      <li class="nav-item"><a class="nav-link" href="#staff-team" data-bs-toggle="tab"><i class="fas fa-user-shield me-2"></i>Staff Team</a></li>
      <li class="nav-item"><a class="nav-link" href="#freeleech-settings" data-bs-toggle="tab"><i class="fas fa-gift me-2"></i>Freeleech Settings</a></li>
      <li class="nav-item"><a class="nav-link" href="index.php?act=cronjobs"><i class="fas fa-clock me-2"></i>Cronjobs</a></li>
    </ul>
  </div>

  <!-- ═══════════════════════════ CONTENT ══════════════════════════════════ -->
  <main class="col-md-9 ms-sm-auto col-lg-10">

    <div class="page-topbar">
      <h1 id="current-tab-title">Tracker Settings</h1>
      <button class="btn btn-primary btn-sm px-3"
              onclick="document.querySelector('.tab-pane.show.active form')?.requestSubmit()">
        <i class="fas fa-save me-1"></i> Save Settings
      </button>
    </div>

    <div class="content-pad">
    <div class="tab-content">

      <!-- ── MAIN SETTINGS ─────────────────────────────────────────────── -->
      <div class="tab-pane fade show active" id="main-settings">
        <form method="post">
          <div class="card mb-4">
            <div class="card-header">Basic Information</div>
            <div class="card-body">

              <div class="mb-3">
                <label class="form-label">Tracker Name</label>
                <div class="input-group">
                  <input type="text" class="form-control" name="configoption[SITENAME]" value="<?= htmlspecialchars($settings['SITENAME'] ?? '') ?>">
                  <span class="input-group-text help-icon" data-bs-toggle="popover" data-bs-title="Tracker Name" data-bs-content="Your tracker display name" data-bs-trigger="hover focus"><i class="fas fa-info-circle"></i></span>
                </div>
              </div>
              <div class="mb-3">
                <label class="form-label">Base URL</label>
                <div class="input-group">
                  <input type="text" class="form-control" name="configoption[BASEURL]" value="<?= htmlspecialchars($settings['BASEURL'] ?? '') ?>" placeholder="https://yourtracker.com">
                  <span class="input-group-text help-icon" data-bs-toggle="popover" data-bs-title="Base URL" data-bs-content="No trailing slash!" data-bs-trigger="hover focus"><i class="fas fa-info-circle"></i></span>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6 mb-3">
                  <label class="form-label">Site Email</label>
                  <input type="email" class="form-control" name="configoption[SITEEMAIL]" value="<?= htmlspecialchars($settings['SITEEMAIL'] ?? '') ?>">
                </div>
                <div class="col-md-6 mb-3">
                  <label class="form-label">Report Email</label>
                  <input type="email" class="form-control" name="configoption[REPORTMAIL]" value="<?= htmlspecialchars($settings['REPORTMAIL'] ?? '') ?>">
                </div>
              </div>
              <div class="mb-3">
                <label class="form-label">Contact Email(s) <small class="text-muted fw-normal" style="text-transform:none;letter-spacing:0">— separate with commas</small></label>
                <input type="text" class="form-control" name="configoption[contactemail]" value="<?= htmlspecialchars($settings['contactemail'] ?? '') ?>">
              </div>
              <div class="mb-3">
                <label class="form-label">Tracker Slogan</label>
                <input type="text" class="form-control" name="configoption[slogan]" value="<?= htmlspecialchars($settings['slogan'] ?? '') ?>">
              </div>
              <div class="row">
                <div class="col-md-6 mb-3">
                  <label class="form-label">Meta Keywords</label>
                  <textarea class="form-control" name="configoption[metakeywords]" rows="3"><?= htmlspecialchars($settings['metakeywords'] ?? '') ?></textarea>
                </div>
                <div class="col-md-6 mb-3">
                  <label class="form-label">Meta Description</label>
                  <textarea class="form-control" name="configoption[metadesc]" rows="3"><?= htmlspecialchars($settings['metadesc'] ?? '') ?></textarea>
                </div>
              </div>

              <div class="section-sub">Site Status</div>
              <div class="mb-3">
                <label class="form-label">Status</label>
                <select class="form-select" id="siteonline" name="configoption[SITEONLINE]">
                  <option value="yes" <?= ($settings['SITEONLINE']??'yes')==='yes'?'selected':'' ?>>🟢 Online</option>
                  <option value="no"  <?= ($settings['SITEONLINE']??'yes')==='no' ?'selected':'' ?>>🔴 Offline / Maintenance</option>
                </select>
              </div>
              <div id="offlineDurationGroup" class="offline-wrap" style="display:<?= ($settings['SITEONLINE']??'yes')==='no'?'block':'none' ?>">
                <?php if ($timeRemaining): ?>
                  <div class="mb-2 small"><i class="fas fa-clock me-1"></i> <?= $timeRemaining ?>
                    <?php if (!$isUnlimited && is_numeric($offlineMinutesValue)): ?>
                      <div class="text-muted mt-1">Back at: <?= date('Y-m-d H:i:s', (int)$offlineMinutesValue) ?></div>
                    <?php endif; ?>
                  </div>
                <?php endif; ?>
                <div class="form-check mb-2">
                  <input class="form-check-input" type="radio" name="offline_mode_type" id="limitedMode" value="limited" <?= !$isUnlimited?'checked':'' ?>>
                  <label class="form-check-label" for="limitedMode">Limited Time</label>
                </div>
                <div class="form-check mb-3">
                  <input class="form-check-input" type="radio" name="offline_mode_type" id="unlimitedMode" value="unlimited" <?= $isUnlimited?'checked':'' ?>>
                  <label class="form-check-label" for="unlimitedMode">Unlimited</label>
                </div>
                <div id="timeLimitGroup" style="display:<?= !$isUnlimited?'block':'none' ?>">
                  <label class="form-label">Duration (minutes)</label>
                  <div class="input-group" style="max-width:220px">
                    <input type="number" min="1" max="1440" class="form-control" name="offline_minutes_input" value="<?= !$isUnlimited?$durationMinutes:30 ?>">
                    <span class="input-group-text">min (max 24h)</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-end mb-2">
            <button class="btn btn-primary px-4" type="submit"><i class="fas fa-save me-1"></i> Save</button>
          </div>
        </form>
      </div>

      <!-- ── TRACKER SETTINGS ──────────────────────────────────────────── -->
      <div class="tab-pane fade" id="tracker-settings">
        <form method="post">
          <div class="card mb-4">
            <div class="card-header">Tracker Configuration</div>
            <div class="card-body">
              <?php
              $yn  = ['yes'=>'Yes','no'=>'No'];
              $yn1 = ['1'=>'Yes','0'=>'No'];
              function fsel(string $n,array $o,string $cur,string $lbl,string $tip=''): void {
                echo '<div class="mb-3"><label class="form-label">'.htmlspecialchars($lbl).'</label><div class="input-group">';
                echo '<select class="form-select" name="configoption['.htmlspecialchars($n).']">';
                foreach($o as $v=>$t) echo '<option value="'.htmlspecialchars((string)$v).'"'.($cur==$v?' selected':'').'>'.htmlspecialchars($t).'</option>';
                echo '</select>';
                if($tip) echo '<span class="input-group-text help-icon" data-bs-toggle="popover" data-bs-title="'.htmlspecialchars($lbl).'" data-bs-content="'.htmlspecialchars($tip).'" data-bs-trigger="hover focus"><i class="fas fa-info-circle"></i></span>';
                echo '</div></div>';
              }
              function ftxt(string $n,string $v,string $lbl,string $tip='',string $type='text'): void {
                echo '<div class="mb-3"><label class="form-label">'.htmlspecialchars($lbl).'</label><div class="input-group">';
                echo '<input type="'.$type.'" class="form-control" name="configoption['.htmlspecialchars($n).']" value="'.htmlspecialchars($v).'">';
                if($tip) echo '<span class="input-group-text help-icon" data-bs-toggle="popover" data-bs-title="'.htmlspecialchars($lbl).'" data-bs-content="'.htmlspecialchars($tip).'" data-bs-trigger="hover focus"><i class="fas fa-info-circle"></i></span>';
                echo '</div></div>';
              }
              $s = $settings;
              ?>
              <div class="row">
                <div class="col-md-6"><?php fsel('useajax',$yn,$s['useajax']??'yes','Active Ajax Features?','AJAX allows live data without page refresh'); ?></div>
                <div class="col-md-6"><?php fsel('use_xmlhttprequest',$yn1,$s['use_xmlhttprequest']??'1','Use XMLHttpRequest'); ?></div>
                <div class="col-md-6"><?php fsel('redirects',$yn1,$s['redirects']??'1','Friendly Redirection Pages'); ?></div>
                <div class="col-md-6"><?php fsel('externalscrape',$yn,$s['externalscrape']??'no','Active External Scrape?'); ?></div>
                <div class="col-md-6"><?php fsel('includeexpeers',$yn,$s['includeexpeers']??'no','Include External Peers?'); ?></div>
                <div class="col-md-6"><?php fsel('MEMBERSONLY',$yn,$s['MEMBERSONLY']??'yes','Registered Members Only?'); ?></div>
                <div class="col-md-6"><?php fsel('seourls',$yn,$s['seourls']??'no','Active SEO'); ?></div>
                <div class="col-md-6"><?php fsel('gzipcompress',$yn,$s['gzipcompress']??'yes','GZIP Compression Enabled','Compresses pages for faster delivery'); ?></div>
                <div class="col-md-6"><?php fsel('jumptopagemultipage',$yn1,$s['jumptopagemultipage']??'1','Show Jump To Page in Pagination'); ?></div>
                <div class="col-md-6"><?php fsel('hitrun',$yn,$s['hitrun']??'yes','HIT & RUN System Enabled?'); ?></div>
              </div>

              <div class="section-sub">Limits & Paths</div>
              <div class="row">
                <div class="col-md-4"><?php ftxt('maxloginattempts',$s['maxloginattempts']??'5','Max. Login Attempts','Ban IPs over this limit','number'); ?></div>
                <div class="col-md-4"><?php ftxt('maxmultipagelinks',$s['maxmultipagelinks']??'5','Max Pagination Links','','number'); ?></div>
                <div class="col-md-4"><?php ftxt('wolcutoffmins',$s['wolcutoffmins']??'15','Cut-off Time (mins)','Minutes before user marked offline','number'); ?></div>
                <div class="col-md-4"><?php ftxt('hitrun_ratio',$s['hitrun_ratio']??'0.5','Min. Ratio for H&R'); ?></div>
                <div class="col-md-4"><?php ftxt('hitrun_gig',$s['hitrun_gig']??'5','Min. GB for H&R','','number'); ?></div>
                <div class="col-md-4"><?php ftxt('max_torrent_size',$s['max_torrent_size']??'','Max. Torrent Size','10 GB = 10*1024*1024'); ?></div>
                <div class="col-md-6"><?php ftxt('securehash',$s['securehash']??'','Secure Hash','Changing this forces all users to re-login'); ?></div>
                <div class="col-md-6"><?php ftxt('announce_urls[]',$announce_url,'Announce URL','Full URL to announce.php'); ?></div>
                <div class="col-md-6"><?php ftxt('torrent_dir',$s['torrent_dir']??'','Torrent Directory Path','No trailing slash'); ?></div>
                <div class="col-md-6"><?php ftxt('pic_base_url',$s['pic_base_url']??'','Image Directory Path','With trailing slash'); ?></div>
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-end mb-2"><button class="btn btn-primary px-4" type="submit"><i class="fas fa-save me-1"></i> Save</button></div>
        </form>
      </div>

      <!-- ── DATE & TIME ───────────────────────────────────────────────── -->
      <div class="tab-pane fade" id="date-time">
        <form method="post">
          <div class="card mb-4">
            <div class="card-header">Date & Time Settings</div>
            <div class="card-body">
              <div class="row">
                <div class="col-md-6"><?php ftxt('dateformat',$settings['dateformat']??'d M Y','Date Format','PHP date() format'); ?></div>
                <div class="col-md-6"><?php ftxt('timeformat',$settings['timeformat']??'H:i','Time Format'); ?></div>
                <div class="col-md-6"><?php ftxt('regdateformat',$settings['regdateformat']??'d M Y','Registered Date Format'); ?></div>
                <div class="col-md-6"><?php ftxt('datetimesep',$settings['datetimesep']??', ','Date/Time Separator'); ?></div>
                <div class="col-md-6"><?php fsel('dstcorrection',['1'=>'Yes','0'=>'No'],$settings['dstcorrection']??'0','Day Light Savings Time?'); ?></div>
                <div class="col-md-6">
                  <div class="mb-3"><label class="form-label">Default Timezone Offset</label>
                    <select class="form-select" name="configoption[timezoneoffset]">
                      <?php foreach(['-12','-11','-10','-9','-8','-7','-6','-5','-4','-3.5','-3','-2','-1','0','+1','+2','+3','+3.5','+4','+4.5','+5','+5.5','+5.75','+6','+7','+8','+9','+9.5','+10','+10.5','+11','+12'] as $tz):
                        $sel = ($settings['timezoneoffset']??'0')==$tz?' selected':'';
                        echo "<option value=\"{$tz}\"{$sel}>GMT {$tz}</option>";
                      endforeach; ?>
                    </select>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-end mb-2"><button class="btn btn-primary px-4" type="submit"><i class="fas fa-save me-1"></i> Save</button></div>
        </form>
      </div>

      <!-- ── COOKIES ───────────────────────────────────────────────────── -->
      <div class="tab-pane fade" id="cookie-settings">
        <form method="post">
          <div class="card mb-4">
            <div class="card-header">Cookie Settings</div>
            <div class="card-body">
              <div class="row">
                <div class="col-md-6"><?php ftxt('cookiedomain',$settings['cookiedomain']??'','Cookie Domain','Start with a dot for all subdomains'); ?></div>
                <div class="col-md-6"><?php ftxt('cookiepath',$settings['cookiepath']??'/','Cookie Path'); ?></div>
                <div class="col-md-6"><?php ftxt('cookieprefix',$settings['cookieprefix']??'','Cookie Prefix'); ?></div>
                <div class="col-md-6"><?php fsel('cookiesecureflag',['1'=>'Yes','0'=>'No'],$settings['cookiesecureflag']??'0','Secure Cookie Flag','Only enable on HTTPS'); ?></div>
                <div class="col-md-6"><?php fsel('cookiesamesiteflag',['1'=>'Yes','0'=>'No'],$settings['cookiesamesiteflag']??'0','SameSite Cookie Flag','Prevents CSRF attacks'); ?></div>
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-end mb-2"><button class="btn btn-primary px-4" type="submit"><i class="fas fa-save me-1"></i> Save</button></div>
        </form>
      </div>

      <!-- ── AVATARS ───────────────────────────────────────────────────── -->
      <div class="tab-pane fade" id="avatar-settings">
        <form method="post">
          <div class="card mb-4">
            <div class="card-header">Avatar Settings</div>
            <div class="card-body">
              <div class="row">
                <div class="col-md-6"><?php ftxt('useravatar',$settings['useravatar']??'','Default User Avatar','Used when user has no avatar'); ?></div>
                <div class="col-md-6"><?php ftxt('useravatardims',$settings['useravatardims']??'40x40','Default Avatar Dimensions','40x40 or 40|40'); ?></div>
                <div class="col-md-6"><?php ftxt('maxavatardims',$settings['maxavatardims']??'100x100','Maximum Avatar Dimensions'); ?></div>
                <div class="col-md-6"><?php ftxt('avataruploadpath',$settings['avataruploadpath']??'','Avatar Upload Path'); ?></div>
                <div class="col-md-6"><?php ftxt('avatarsize',$settings['avatarsize']??'102400','Maximum Avatar Size (bytes)','','number'); ?></div>
                <div class="col-md-6"><?php fsel('allowremoteavatars',['1'=>'Yes','0'=>'No'],$settings['allowremoteavatars']??'0','Allow Remote Avatars','Exposes your server IP'); ?></div>
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-end mb-2"><button class="btn btn-primary px-4" type="submit"><i class="fas fa-save me-1"></i> Save</button></div>
        </form>
      </div>

      <!-- ── SECURITY ──────────────────────────────────────────────────── -->
      <div class="tab-pane fade" id="security-settings">
        <form method="post">
          <div class="card mb-4">
            <div class="card-header">Security Settings</div>
            <div class="card-body">
              <div class="row">
                <div class="col-md-6"><?php fsel('aggressivecheckip',$yn,$settings['aggressivecheckip']??'no','Aggressive IP Ban?'); ?></div>
                <div class="col-md-6"><?php fsel('aggressivecheckemail',$yn,$settings['aggressivecheckemail']??'no','Aggressive EMAIL Ban?'); ?></div>
                <div class="col-md-6"><?php fsel('iplog1',$yn,$settings['iplog1']??'yes','Save User IP?','Log IP changes to DB'); ?></div>
                <div class="col-md-6"><?php fsel('ctracker',$yn,$settings['ctracker']??'yes','Cracker Tracker Protection?','URL protection against attacks'); ?></div>
                <div class="col-md-6"><?php fsel('vkeyword',['yes'=>'Yes','no'=>'No'],$vkeyword,'Virtual Keyboard Enabled?','Prevents keylogger attacks'); ?></div>
                <div class="col-md-6"><?php fsel('privatetrackerpatch',$yn,$settings['privatetrackerpatch']??'no','Private Tracker Patch Enabled?'); ?></div>
              </div>

              <div class="section-sub">Image Verification (CAPTCHA)</div>
              <div class="mb-3">
                <label class="form-label">Image Verification Enabled?</label>
                <div class="input-group">
                  <select class="form-select" name="configoption[iv]">
                    <option value="yes"       <?= $iv==='yes'      ?'selected':''?>>Yes, use Image Verification (GD/GD2)</option>
                    <option value="reCAPTCHA" <?= $iv==='reCAPTCHA'?'selected':''?>>Yes, use reCAPTCHA™</option>
                    <option value="no"        <?= $iv==='no'       ?'selected':''?>>No, disabled</option>
                  </select>
                  <span class="input-group-text help-icon" data-bs-toggle="popover" data-bs-title="Image Verification" data-bs-content="GD or GD2 library required" data-bs-trigger="hover focus"><i class="fas fa-info-circle"></i></span>
                </div>
              </div>
              <?php if ($iv === 'reCAPTCHA'): ?>
              <div class="row">
                <div class="col-md-6"><?php ftxt('reCAPTCHAPublickey',$reCAPTCHAPublickey,'reCAPTCHA™ Public Key'); ?></div>
                <div class="col-md-6"><?php ftxt('reCAPTCHAPrivatekey',$reCAPTCHAPrivatekey,'reCAPTCHA™ Private Key'); ?></div>
                <div class="col-md-6"><?php fsel('reCAPTCHATheme',['red'=>'Red','white'=>'White','blackglass'=>'Black Glass'],$reCAPTCHATheme,'reCAPTCHA™ Theme'); ?></div>
                <div class="col-md-6"><?php fsel('reCAPTCHALanguage',['en'=>'English','nl'=>'Dutch','fr'=>'French','de'=>'German','pt'=>'Portuguese','ru'=>'Russian','es'=>'Spanish','tr'=>'Turkish'],$reCAPTCHALanguage,'reCAPTCHA™ Language'); ?></div>
              </div>
              <?php endif; ?>
            </div>
          </div>
          <div class="d-flex justify-content-end mb-2"><button class="btn btn-primary px-4" type="submit"><i class="fas fa-save me-1"></i> Save</button></div>
        </form>
      </div>

      <!-- ── EMAIL ─────────────────────────────────────────────────────── -->
      <div class="tab-pane fade" id="email-settings">
        <form method="post">
          <div class="card mb-4">
            <div class="card-header">Email Settings</div>
            <div class="card-body">
              <div class="row">
                <div class="col-md-6"><?php fsel('mail_handler',['mail'=>'PHP Mail','smtp'=>'SMTP','sendmail'=>'Sendmail'],$settings['mail_handler']??'mail','Mail Handler'); ?></div>
                <div class="col-md-6"><?php fsel('mail_logging',['0'=>'None','1'=>'Log without content','2'=>'Log everything'],$settings['mail_logging']??'0','Mail Logging'); ?></div>
                <div class="col-md-6"><?php fsel('mail_message_id',['1'=>'Yes','0'=>'No'],$settings['mail_message_id']??'1','Add Message-ID in headers?','Disable on shared hosting if spam issues'); ?></div>
                <div class="col-md-6"><?php ftxt('mail_queue_limit',$settings['mail_queue_limit']??'50','Messages to send from mail queue','Max per cron batch','number'); ?></div>
              </div>
              <?php if (($settings['mail_handler']??'mail')==='smtp'): ?>
              <div class="section-sub">SMTP Configuration</div>
              <div class="row">
                <div class="col-md-6"><?php ftxt('smtp_host',$settings['smtp_host']??'','SMTP Host'); ?></div>
                <div class="col-md-6"><?php ftxt('smtp_user',$settings['smtp_user']??'','SMTP Username'); ?></div>
                <div class="col-md-6">
                  <div class="mb-3"><label class="form-label">SMTP Password</label>
                    <input type="password" class="form-control" name="configoption[smtp_pass]" value="<?= htmlspecialchars($settings['smtp_pass']??'') ?>">
                  </div>
                </div>
                <div class="col-md-6"><?php ftxt('smtp_port',$settings['smtp_port']??'587','SMTP Port','25 / 465 (SSL) / 587 (TLS)','number'); ?></div>
                <div class="col-md-6"><?php fsel('secure_smtp',['0'=>'No encryption','1'=>'SSL encryption','2'=>'TLS encryption'],$settings['secure_smtp']??'0','Secure SMTP'); ?></div>
              </div>
              <?php endif; ?>
            </div>
          </div>
          <div class="d-flex justify-content-end mb-2"><button class="btn btn-primary px-4" type="submit"><i class="fas fa-save me-1"></i> Save</button></div>
        </form>
      </div>

      <!-- ── ANNOUNCE ──────────────────────────────────────────────────── -->
      <div class="tab-pane fade" id="announce-settings">
        <form method="post">
          <div class="card mb-4">
            <div class="card-header">ANNOUNCE Settings</div>
            <div class="card-body">
              <div class="row">
                <div class="col-md-6"><?php fsel('announce_actions',$yn,(string)$announce_actions,'Log Cheat Attempts?','Disable for better performance'); ?></div>
                <div class="col-md-6"><?php fsel('aggressivecheat',$yn,(string)$aggressivecheat,'Aggressive Cheat Detection?','Detects RatioMaster etc.'); ?></div>
                <div class="col-md-6"><?php fsel('nc',$yn,(string)$nc,'Disable DL/UL?','Block non-connectable peers'); ?></div>
                <div class="col-md-6"><?php fsel('bannedclientdetect',$yn,(string)$bannedclientdetect,'Banned Client Detection?'); ?></div>
                <div class="col-md-6"><?php fsel('detectbrowsercheats',$yn,(string)$detectbrowsercheats,'Detect Browser Cheats?'); ?></div>
                <div class="col-md-6"><?php fsel('checkconnectable',$yn,(string)$checkconnectable,'Detect Connectable?','Decreases performance'); ?></div>
                <div class="col-md-6"><?php fsel('checkip',$yn,(string)$checkip,'Check IP?','Match DB IP vs client IP'); ?></div>
                <div class="col-md-6"><?php ftxt('announce_wait',(string)$announce_wait,'Min. Announce Refresh Time?','Flood limit in seconds'); ?></div>
                <div class="col-md-6"><?php ftxt('announce_interval',(string)$announce_interval,'Announce Interval?','Higher = better performance'); ?></div>
                <div class="col-md-6"><?php ftxt('max_rate',(string)$max_rate,'Max. Transfer Rate?','Flag suspicious speeds above this'); ?></div>
              </div>
              <div class="mb-3">
    <label class="form-label">Allowed Clients</label>
    <div class="input-group">
        <textarea class="form-control" name="configoption[allowed_clients]" rows="4"><?= htmlspecialchars((string)$allowed_clients) ?></textarea>
        <span class="input-group-text help-icon"
              data-bs-toggle="popover"
              data-bs-title="Allowed Clients"
              data-bs-content="Whitelist of allowed clients"
              data-bs-trigger="hover focus">
            <i class="fas fa-info-circle"></i>
        </span>
    </div>
</div>
              <div class="section-sub">Database Connection (Announce)</div>
              <div class="row">
                <div class="col-md-6"><?php ftxt('mysql_host',(string)$mysql_host,'MYSQL Host'); ?></div>
                <div class="col-md-6"><?php ftxt('mysql_user',(string)$mysql_user,'MYSQL User'); ?></div>
                <div class="col-md-6">
                  <div class="mb-3"><label class="form-label">MYSQL Password</label>
                    <input type="password" class="form-control" name="configoption[mysql_pass]" placeholder="Leave blank to keep current">
                  </div>
                </div>
                <div class="col-md-6"><?php ftxt('mysql_db',(string)$mysql_db,'MYSQL Database Name'); ?></div>
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-end mb-2">
            <button class="btn btn-primary px-4" type="submit" name="save_announce"><i class="fas fa-save me-1"></i> Save Changes</button>
          </div>
        </form>
      </div>

      <!-- ── KPS ───────────────────────────────────────────────────────── -->
      <div class="tab-pane fade" id="kps-settings">
        <form method="post">
          <div class="card mb-4">
            <div class="card-header">KPS (Bonus Points) System Settings</div>
            <div class="card-body">
              <div class="mb-3">
                <label class="form-label">KPS System Enabled?</label>
                <div class="input-group">
                  <select class="form-select" name="configoption[bonus]">
                    <option value="enable"      <?= $bonus==='enable'     ?'selected':''?>>Yes, Enabled</option>
                    <option value="disablesave" <?= $bonus==='disablesave'?'selected':''?>>No, But Save Points</option>
                    <option value="disable"     <?= $bonus==='disable'    ?'selected':''?>>No, Disabled</option>
                  </select>
                  <span class="input-group-text help-icon" data-bs-toggle="popover" data-bs-title="KPS System" data-bs-content="Users trade points on KPS page" data-bs-trigger="hover focus"><i class="fas fa-info-circle"></i></span>
                </div>
              </div>

              <div class="section-sub">Point Values</div>
              <div class="row">
                <div class="col-md-4"><?php ftxt('kpsseed',$kpsseed,'Seed Point'); ?></div>
                <div class="col-md-4"><?php ftxt('kpsupload',$kpsupload,'Upload Point'); ?></div>
                <div class="col-md-4"><?php ftxt('kpscomment',$kpscomment,'Post/Comment/Thread Point'); ?></div>
                <div class="col-md-4"><?php ftxt('kpsthanks',$kpsthanks,'Thanks Point'); ?></div>
                <div class="col-md-4"><?php ftxt('kpsrate',$kpsrate,'Rating Point'); ?></div>
                <div class="col-md-4"><?php ftxt('kpspoll',$kpspoll,'Poll Point'); ?></div>
                <div class="col-md-4"><?php ftxt('kpsmaxpoint',$kpsmaxpoint,'Max. Bonus Point'); ?></div>
              </div>

              <div class="section-sub">Feature Toggles</div>
              <div class="row">
                <div class="col-md-4"><?php fsel('kpsinvite',$yn,$kpsinvite,'Enable Invite Usage?'); ?></div>
                <div class="col-md-4"><?php fsel('kpstitle',$yn,$kpstitle,'Enable Custom Title Usage?'); ?></div>
                <div class="col-md-4"><?php fsel('kpsvip',$yn,$kpsvip,'Enable VIP Status Usage?'); ?></div>
                <div class="col-md-4"><?php fsel('kpsgift',$yn,$kpsgift,'Enable Give A Karma Gift?'); ?></div>
                <div class="col-md-4"><?php fsel('kpswarning',$yn,$kpswarning,'Enable Remove Warning Usage?'); ?></div>
                <div class="col-md-4"><?php fsel('kpsratiofix',$yn,$kpsratiofix,'Enable Fix Torrent Ratio Usage?'); ?></div>
              </div>

              <div class="section-sub">Birthday Reward Settings</div>
              <div class="row">
                <div class="col-md-6"><?php fsel('bdayreward',$yn,$bdayreward,'Birthday Reward System Enabled?'); ?></div>
                <div class="col-md-6"><?php fsel('bdayrewardtype',['freeleech'=>'Free Leech','silverleech'=>'Silver Leech','doubleupload'=>'x2 Upload'],$bdayrewardtype,'Birthday Reward Type'); ?></div>
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-end mb-2">
            <button class="btn btn-primary px-4" type="submit" name="save_kps"><i class="fas fa-save me-1"></i> Save Changes</button>
          </div>
        </form>
      </div>

      <!-- ── CLEANUP ───────────────────────────────────────────────────── -->
      <div class="tab-pane fade" id="user-management-settings">
        <form method="post">
          <div class="card mb-4">
            <div class="card-header">Cleanup Settings</div>
            <div class="card-body">
              <div class="section-sub">Automatic Invites</div>
              <div class="row">
                <div class="col-md-6"><?php fsel('ai',$yn,$ai,'Automatic Invite?'); ?></div>
                <div class="col-md-6"><?php ftxt('autoinvitetime',$autoinvitetime,'Automatic Invite Time (days)','','number'); ?></div>
              </div>

              <div class="section-sub">Torrents</div>
              <?php ftxt('max_dead_torrent_time',$max_dead_torrent_time,'Mark Torrents Invisible After (days)','Torrent Last Action < X days','number'); ?>

              <div class="section-sub">User Promotion Settings</div>
              <div class="row">
                <div class="col-md-4"><?php ftxt('promote_gig_limit',$promote_gig_limit,'Promote Users GB Limit','0 = disabled','number'); ?></div>
                <div class="col-md-4"><?php ftxt('promote_min_ratio',$promote_min_ratio,'Promote Users RATIO Limit'); ?></div>
                <div class="col-md-4"><?php ftxt('promote_min_reg_days',$promote_min_reg_days,'Promote Users DAYS Limit','','number'); ?></div>
                <div class="col-md-4"><?php ftxt('demote_min_ratio',$demote_min_ratio,'Demote Users RATIO Limit'); ?></div>
                <div class="col-md-4"><?php ftxt('referrergift',$referrergift,'Referrer Gift (GB)','','number'); ?></div>
              </div>

              <div class="section-sub">User Warning Settings</div>
              <div class="row">
                <div class="col-md-4"><?php ftxt('leechwarn_min_ratio',$leechwarn_min_ratio,'Warn User MIN. Ratio'); ?></div>
                <div class="col-md-4"><?php ftxt('leechwarn_gig_limit',$leechwarn_gig_limit,'Warn User GB Limit','','number'); ?></div>
                <div class="col-md-4"><?php ftxt('leechwarn_length',$leechwarn_length,'Warning Length (weeks)','','number'); ?></div>
                <div class="col-md-4"><?php ftxt('leechwarn_remove_ratio',$leechwarn_remove_ratio,'Remove Warning Min. Ratio'); ?></div>
                <div class="col-md-4"><?php ftxt('ban_user_limit',$ban_user_limit,'Ban Warned Users After X Warnings','','number'); ?></div>
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-end mb-2">
            <button class="btn btn-primary px-4" type="submit" name="save_user_management"><i class="fas fa-save me-1"></i> Save Changes</button>
          </div>
        </form>
      </div>

      <!-- ── REGISTRATION ──────────────────────────────────────────────── -->
      <div class="tab-pane fade" id="registration-settings">
        <form method="post">
          <div class="card mb-4">
            <div class="card-header">Registration Settings</div>
            <div class="card-body">
              <div class="section-sub">Registration System</div>
              <div class="row">
                <div class="col-md-6"><?php fsel('invitesystem',['on'=>'Enabled','off'=>'Disabled'],$invitesystem,'Invite System'); ?></div>
                <div class="col-md-6"><?php fsel('regtype',['invite'=>'Invite System','instant'=>'Instant Activation','verify'=>'Email Verification','randompass'=>'Random Password','admin'=>'Admin Activation','both'=>'Email + Admin Activation'],$regtype,'Registration Method'); ?></div>
                <div class="col-md-6"><?php fsel('disableregs',['1'=>'Yes','0'=>'No'],$disableregs,'Disable Registrations'); ?></div>
                <div class="col-md-6"><?php ftxt('maxusers',$maxusers,'Max Users (0 = unlimited)','','number'); ?></div>
              </div>

              <div class="section-sub">Username Requirements</div>
              <div class="row">
                <div class="col-md-4"><?php ftxt('minnamelength',$minnamelength,'Min Username Length','','number'); ?></div>
                <div class="col-md-4"><?php ftxt('maxnamelength',$maxnamelength,'Max Username Length','','number'); ?></div>
                <div class="col-md-4"><?php ftxt('maxip',$maxip,'Max. IPs','0 = disabled','number'); ?></div>
              </div>
              <div class="mb-3">
                <label class="form-label">Banned Usernames</label>
                <textarea class="form-control" name="configoption[illegalusernames]" rows="3"><?= htmlspecialchars($illegalusernames) ?></textarea>
              </div>

              <div class="section-sub">Password Requirements</div>
              <div class="row">
                <div class="col-md-4"><?php ftxt('minpasswordlength',$minpasswordlength,'Min Password Length','','number'); ?></div>
                <div class="col-md-4"><?php ftxt('maxpasswordlength',$maxpasswordlength,'Max Password Length','','number'); ?></div>
                <div class="col-md-4"><?php fsel('requirecomplexpasswords',['1'=>'Required','0'=>'Not Required'],$requirecomplexpasswords,'Complex Passwords'); ?></div>
              </div>

              <div class="section-sub">Security & Bonuses</div>
              <div class="row">
                <div class="col-md-4"><?php ftxt('failedlogincount',$failedlogincount,'Max Failed Logins','0 = disabled','number'); ?></div>
                <div class="col-md-4"><?php fsel('failedlogintext',['1'=>'Yes','0'=>'No'],$failedlogintext,'Display Failed Login Count'); ?></div>
                <div class="col-md-4"><?php fsel('username_method',['0'=>'Username Only','1'=>'Email Only','2'=>'Both'],$username_method,'Allowed Login Methods'); ?></div>
                <div class="col-md-4"><?php fsel('r_verification',$yn,$r_verification,'Verification Fields'); ?></div>
                <div class="col-md-4"><?php fsel('coppa',['enabled'=>'Enabled','deny'=>'Deny under 13','disabled'=>'Disabled'],$coppa,'COPPA Compliance'); ?></div>
                <div class="col-md-4">
                  <div class="mb-3"><label class="form-label">Default Usergroup</label>
                    <select class="form-select" name="configoption[_d_usergroup]">
                      <?php $gq = $db->sql_query('SELECT gid, title, namestyle FROM usergroups');
                      while ($g = mysqli_fetch_assoc($gq)) {
                        $sel = $_d_usergroup == $g['gid'] ? ' selected' : '';
                        echo "<option value=\"{$g['gid']}\"{$sel}>" . htmlspecialchars(strip_tags($g['title'])) . "</option>";
                      } ?>
                    </select>
                  </div>
                </div>
                <div class="col-md-4"><?php ftxt('invite_count',$invite_count,'Initial Invites','0 = disabled','number'); ?></div>
                <div class="col-md-4"><?php ftxt('autogigsignup',$autogigsignup,'Auto GB on Signup','0 = disabled','number'); ?></div>
                <div class="col-md-4"><?php ftxt('autosbsignup',$autosbsignup,'Auto SeedBonus','0 = disabled','number'); ?></div>
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-end mb-2">
            <button class="btn btn-primary px-4" type="submit" name="save_registration"><i class="fas fa-save me-1"></i> Save Changes</button>
          </div>
        </form>
      </div>

      <!-- ── STAFF TEAM ────────────────────────────────────────────────── -->
      <div class="tab-pane fade" id="staff-team">
        <div class="card mb-4 shadow-sm">
          <div class="card-header d-flex justify-content-between align-items-center">
            <span><i class="fas fa-users-cog me-2"></i> Staff Team Management</span>
            <span class="badge bg-primary rounded-pill"><?= count($staffarray) ?> members</span>
          </div>
          <div class="card-body">
            <div class="alert alert-info mb-4">
              <i class="fas fa-lightbulb me-2"></i>
              <strong>Tip:</strong> Type a username — ID auto-fills if found. Use <strong>Find User</strong> for manual search.
            </div>
            <form method="post" action="<?= htmlspecialchars($_SERVER['PHP_SELF']) ?>">
              <datalist id="staffNames">
                <?php foreach ($availableStaff as $st): ?>
                <option value="<?= htmlspecialchars($st['username']) ?>"><?= htmlspecialchars($st['username']) ?> (<?= htmlspecialchars($st['group'] ?? '') ?>)</option>
                <?php endforeach; ?>
              </datalist>
              <div class="table-responsive">
                <table class="table table-striped table-hover align-middle">
                  <thead class="table-dark">
                    <tr><th width="5%">#</th><th width="47%">Username</th><th width="43%">User ID</th><th width="5%">Actions</th></tr>
                  </thead>
                  <tbody>
                    <?php if (!empty($staffarray)): ?>
                      <?php foreach ($staffarray as $i => $st): ?>
                      <tr>
                        <td class="text-center fw-bold"><?= $i + 1 ?></td>
                        <td><input type="text" name="staffnames[]" value="<?= htmlspecialchars($st['name']) ?>" class="form-control" list="staffNames" placeholder="Username"></td>
                        <td><input type="text" name="staffids[]"   value="<?= htmlspecialchars($st['id'])   ?>" class="form-control" placeholder="User ID"></td>
                        <td class="text-center"><button type="button" class="btn btn-sm btn-outline-danger" onclick="this.closest('tr').querySelectorAll('input').forEach(i=>i.value='')"><i class="fas fa-times"></i></button></td>
                      </tr>
                      <?php endforeach; ?>
                    <?php else: ?>
                      <tr><td colspan="4" class="text-center text-muted py-4">No staff members found. Add below.</td></tr>
                    <?php endif; ?>
                    <?php for ($i = 0; $i < 3; $i++): ?>
                    <tr class="table-success">
                      <td class="text-center"><span class="badge bg-success rounded-pill">New</span></td>
                      <td><input type="text" name="staffnames[]" class="form-control" list="staffNames" placeholder="Enter username"></td>
                      <td><input type="text" name="staffids[]"   class="form-control" placeholder="Enter user ID"></td>
                      <td></td>
                    </tr>
                    <?php endfor; ?>
                  </tbody>
                </table>
              </div>
              <div class="d-flex justify-content-between align-items-center mt-3 p-3 bg-light rounded">
                <div class="d-flex gap-2">
                  <button type="button" class="btn btn-outline-primary btn-sm"
                          onclick="window.open('<?= htmlspecialchars($BASEURL) ?>/users.php#searchuser','finduser','toolbar=no,scrollbars=yes,width=800,height=600')">
                    <i class="fas fa-search me-1"></i> Find User
                  </button>
                </div>
                <div class="d-flex align-items-center gap-3">
                  <span class="text-muted small"><i class="fas fa-database me-1"></i><?= count($availableStaff) ?> available staff</span>
                  <button type="submit" name="save_staff" class="btn btn-primary px-4"><i class="fas fa-save me-1"></i> Save Changes</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>

      <!-- ── FREELEECH ─────────────────────────────────────────────────── -->
      <div class="tab-pane fade" id="freeleech-settings">
        <form method="post">
          <div class="card mb-4">
            <div class="card-header"><i class="fas fa-gift me-2"></i> FreeLeech Settings</div>
            <div class="card-body">
              <div class="mb-3">
                <label class="form-label">Select System Type</label>
                <select class="form-select" name="configoption[system]">
                  <option value="freeleech"    <?= ($__FLSTYPE??'')==='freeleech'   ?'selected':''?>>Free Leech</option>
                  <option value="silverleech"  <?= ($__FLSTYPE??'')==='silverleech' ?'selected':''?>>Silver Leech</option>
                  <option value="doubleupload" <?= ($__FLSTYPE??'')==='doubleupload'?'selected':''?>>Double Upload</option>
                </select>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="mb-3"><label class="form-label">Begin Date</label>
                    <div class="input-group">
                      <input type="text" id="startPicker" class="form-control" name="configoption[start]"
                             value="<?= ($__F_START??'')!=='0000-00-00 00:00:00' ? htmlspecialchars($__F_START??'') : '' ?>"
                             placeholder="YYYY-MM-DD HH:MM:SS">
                      <span class="input-group-text"><i class="bi bi-calendar"></i></span>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="mb-3"><label class="form-label">End Date</label>
                    <div class="input-group">
                      <input type="text" id="endPicker" class="form-control" name="configoption[end]"
                             value="<?= ($__F_END??'')!=='0000-00-00 00:00:00' ? htmlspecialchars($__F_END??'') : '' ?>"
                             placeholder="YYYY-MM-DD HH:MM:SS">
                      <span class="input-group-text"><i class="bi bi-calendar"></i></span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-end mb-2">
            <button class="btn btn-primary px-4" type="submit" name="save_freeleech"><i class="fas fa-save me-1"></i> Save Changes</button>
          </div>
        </form>
      </div>

    </div><!-- /.tab-content -->
    </div><!-- /.content-pad -->
  </main>
</div>
</div>


<!-- Flatpickr -->
<link rel="stylesheet" href="<?= $BASEURL ?>/admin/templates/airbnb.css">
<script src="<?= $BASEURL ?>/admin/scripts/flatpickr.js"></script>

<!-- Pass PHP data to JavaScript (должен быть ДО загрузки admin-settings.js) -->
<script>
// Pass staff data from PHP to JavaScript
const staffData = <?= json_encode(array_map(fn($s) => ['id' => $s['id'], 'username' => $s['username']], $availableStaff)) ?>;
</script>

<!-- Include the external JavaScript file (ДОЛЖЕН быть ПОСЛЕ определения staffData) -->
<script src="<?= $BASEURL ?>/admin/scripts/admin-settings.js"></script>



<?php stdfoot(); ?>