<?php #DO NOT EDIT THIS FILE, PLEASE USE THE SETTINGS PANEL!!
if(!defined('IN_ANNOUNCE')) die('Hacking attempt!');

$announce_actions = 'yes';
$aggressivecheat = 'yes';
$nc = 'no';
$announce_wait = '30';
$announce_interval = '900';
$max_rate = '2097152';
$bannedclientdetect = 'no';
$allowed_clients = '-UT1610-,-AZ3034-,-UT1750-';
$detectbrowsercheats = 'no';
$checkconnectable = 'no';
$checkip = 'no';
$mysql_host = 'localhost';
$mysql_user = 'root';
$mysql_pass = 'megarave1995';
$mysql_db = 'tracker';
$BASEURL = 'https://artcore-gangsta.eu';
$SITENAME = 'ArtCore Gangsta';
$privatetrackerpatch = 'yes';
$gzipcompress = 'no';
$charset = 'UTF-8';
$aggressivecheckip = 'no';
$snatchmod = 'yes';
$bonus = 'enable';
$kpsseed = '5.0';
$bdayreward = 'yes';
$bdayrewardtype = 'freeleech';
?>