-- =====================================================
-- Install Data
-- Все базовые данные для новой установки
-- =====================================================

-- attachtypes
INSERT IGNORE INTO `attachtypes` (`atid`, `name`, `mimetype`, `extension`, `maxsize`, `icon`, `enabled`, `forcedownload`, `groups`, `forums`, `avatarfile`) VALUES
(1, 'ZIP File', 'application/zip', 'zip', 1024, '<i class=\"fas fa-file-archive\" style=\"color: #e67e22;\"></i>', 1, 0, '-1', '-1', 0),
(2, 'JPG Image', 'image/jpeg', 'jpg', 5000, '<i class=\"fas fa-file-image\" style=\"color: #e74c3c;\"></i>', 1, 0, '-1', '-1', 1),
(3, 'Text Document', 'text/plain', 'txt', 200, '<i class=\"fas fa-file-alt\" style=\"color: #95a5a6;\"></i>', 1, 0, '-1', '-1', 0),
(4, 'GIF Image', 'image/gif', 'gif', 10000, '<i class=\"fas fa-file-image\" style=\"color: #9b59b6;\"></i>', 1, 0, '-1', '-1', 1),
(5, 'Adobe Photoshop File', 'application/x-photoshop', 'psd', 1024, '<i class=\"fas fa-file-image\" style=\"color: #3498db;\"></i>', 1, 0, '-1', '-1', 0),
(6, 'PHP File', 'application/x-httpd-php', 'php', 500, '<i class=\"fab fa-php\" style=\"color: #8892BF;\"></i>', 1, 0, '-1', '-1', 0),
(7, 'PNG Image', 'image/png', 'png', 500, '<i class=\"fas fa-file-image\" style=\"color: #e74c3c;\"></i>', 1, 0, '-1', '-1', 1),
(8, 'Microsoft Word Document', 'application/msword', 'doc', 1024, '<i class=\"fas fa-file-word\" style=\"color: #2b579a;\"></i>', 1, 0, '-1', '-1', 0),
(9, 'HTM File', 'text/html', 'htm', 100, '<i class=\"fab fa-html5\" style=\"color: #e34c26;\"></i>', 1, 0, '-1', '-1', 0),
(10, 'HTML File', 'text/html', 'html', 100, '<i class=\"fab fa-html5\" style=\"color: #e34c26;\"></i>', 1, 0, '-1', '-1', 0),
(11, 'JPEG Image', 'image/jpeg', 'jpeg', 5000, '<i class=\"fas fa-file-image\" style=\"color: #e74c3c;\"></i>', 1, 0, '-1', '-1', 1),
(12, 'GZIP Compressed File', 'application/x-gzip', 'gz', 1024, '<i class=\"fas fa-file-archive\" style=\"color: #e67e22;\"></i>', 1, 0, '-1', '-1', 0),
(13, 'TAR Compressed File', 'application/x-tar', 'tar', 1024, '<i class=\"fas fa-file-archive\" style=\"color: #e67e22;\"></i>', 1, 0, '-1', '-1', 0),
(14, 'CSS Stylesheet', 'text/css', 'css', 100, '<i class=\"fab fa-css3\" style=\"color: #264de4;\"></i>', 1, 0, '-1', '-1', 0),
(15, 'Adobe Acrobat PDF', 'application/pdf', 'pdf', 2048, '<i class=\"fas fa-file-pdf\" style=\"color: #e74c3c;\"></i>', 1, 0, '-1', '-1', 0),
(16, 'Bitmap Image', 'image/bmp', 'bmp', 500, '<i class=\"fas fa-file-image\" style=\"color: #2c3e50;\"></i>', 1, 0, '', '', 0),
(17, 'Microsoft Word 2007 Document', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'docx', 1024, '<i class=\"fas fa-file-word\" style=\"color: #2b579a;\"></i>', 1, 0, '-1', '-1', 0),
(18, 'Microsoft Excel Document', 'application/vnd.ms-excel', 'xls', 1024, '<i class=\"fas fa-file-excel\" style=\"color: #217346;\"></i>', 1, 0, '-1', '-1', 0),
(19, 'Microsoft Excel 2007 Document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'xlsx', 1024, '<i class=\"fas fa-file-excel\" style=\"color: #217346;\"></i>', 1, 0, '-1', '-1', 0),
(20, 'Microsoft PowerPoint Document', 'application/vnd.ms-powerpoint', 'ppt', 1024, '<i class=\"fas fa-file-powerpoint\" style=\"color: #d24726;\"></i>', 1, 0, '-1', '-1', 0),
(21, 'Microsoft PowerPoint 2007 Document', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'pptx', 1024, '<i class=\"fas fa-file-powerpoint\" style=\"color: #d24726;\"></i>', 1, 0, '-1', '-1', 0),
(23, 'WEBP image', 'image/webp', 'webp', 5000, '<i class=\"fas fa-file-image\" style=\"color: #1abc9c;\"></i>', 1, 0, '-1', '-1', 1),
(24, 'Adobe Shockwave Player', 'application/x-director', 'dir', 5555, '<i class=\"fas fa-file-video\" style=\"color: #9b59b6;\"></i>', 1, 0, '', '', 0),
(25, 'WinRAR Archive', 'application/x-rar-compressed', 'rar', 1024, '<i class=\"fas fa-file-archive\" style=\"color: #d35400;\"></i>', 1, 0, '-1', '-1', 0),
(26, '7-Zip Archive', 'application/x-7z-compressed', '7z', 1024, '<i class=\"fas fa-file-archive\" style=\"color: #f39c12;\"></i>', 1, 0, '-1', '-1', 0),
(27, 'Windows Executable', 'application/x-msdownload', 'exe', 5120, '<i class=\"fas fa-cogs\" style=\"color: #7f8c8d;\"></i>', 1, 0, '-1', '-1', 0),
(28, 'MP3 Audio', 'audio/mpeg', 'mp3', 10240, '<i class=\"fas fa-file-audio\" style=\"color: #8e44ad;\"></i>', 1, 0, '-1', '-1', 0),
(29, 'MP4 Video', 'video/mp4', 'mp4', 20480, '<i class=\"fas fa-file-video\" style=\"color: #c0392b;\"></i>', 1, 0, '-1', '-1', 0),
(30, 'SVG Image', 'image/svg+xml', 'svg', 1000, '<i class=\"fas fa-file-image\" style=\"color: #ff6b6b;\"></i>', 1, 0, '-1', '-1', 1),
(31, 'JavaScript File', 'application/javascript', 'js', 500, '<i class=\"fab fa-js\" style=\"color: #f7df1e;\"></i>', 1, 0, '-1', '-1', 0),
(32, 'JSON File', 'application/json', 'json', 500, '<i class=\"fas fa-code\" style=\"color: #f7df1e;\"></i>', 1, 0, '-1', '-1', 0),
(33, 'XML File', 'application/xml', 'xml', 500, '<i class=\"fas fa-code\" style=\"color: #e34c26;\"></i>', 1, 0, '-1', '-1', 0),
(34, 'Python File', 'text/x-python', 'py', 500, '<i class=\"fab fa-python\" style=\"color: #3776ab;\"></i>', 1, 0, '-1', '-1', 0),
(35, 'Java File', 'text/x-java', 'java', 500, '<i class=\"fab fa-java\" style=\"color: #007396;\"></i>', 1, 0, '-1', '-1', 0),
(36, 'C++ File', 'text/x-c++', 'cpp', 500, '<i class=\"fas fa-file-code\" style=\"color: #00599c;\"></i>', 1, 0, '-1', '-1', 0),
(37, 'WordPress Theme', 'application/zip', 'zip', 10240, '<i class=\"fab fa-wordpress\" style=\"color: #21759b;\"></i>', 1, 0, '-1', '-1', 0);

-- banfilters
INSERT IGNORE INTO `banfilters` (`fid`, `filter`, `type`, `lastuse`, `dateline`) VALUES
(148, 'aaaa@aol.com', 3, 0, 1774539315);

-- bonus
INSERT IGNORE INTO `bonus` (`id`, `bonusname`, `points`, `description`, `art`, `menge`) VALUES
(1, '1.0 GB Uploaded', 600.0, 'Exchange points for upload credit.', 'traffic', 1073741824),
(2, '2.5 GB Uploaded', 900.0, 'Exchange points for upload credit.', 'traffic', 2684354560),
(3, '5 GB Uploaded', 1500.0, 'Exchange points for upload credit.', 'traffic', 5368709120),
(4, 'Get Invites', 400.0, 'Exchange points for invites.', 'invite', 3),
(5, 'Custom Title!', 1000.0, 'Buy custom title.', 'title', 1),
(6, 'VIP Status', 5000.0, 'Buy VIP status for one month.', 'class', 1),
(7, 'Give A Karma Gift', 250.0, 'Send a gift to a friend.', 'gift_1', 1073741824),
(8, 'Remove Warning', 400.0, 'Remove a warning from your account.', 'warning', 1),
(9, 'Fix Torrent Ratio', 2000.0, 'Get 1:1 ratio on a specific torrent.', 'ratiofix', 1);

-- categories
INSERT IGNORE INTO `categories` (`id`, `name`, `cat_desc`, `minclassread`, `type`, `pid`, `icon`) VALUES
(1, '1080p', '', 0, 'c', 0, 'fa-solid fa-film fa-shake'),
(2, 'BluRay', '', 0, 'c', 0, 'fa-solid fa-compact-disc fa-spin'),
(3, 'UltraHD', '', 0, 'c', 0, 'fa-solid fa-satellite-dish'),
(4, '2160p', '', 0, 'c', 0, 'fa-solid fa-clapperboard'),
(5, '720p', '', 0, 'c', 0, 'fa-solid fa-tv');

-- countries
INSERT IGNORE INTO `countries` (`id`, `name`, `flagpic`) VALUES
(1, 'Sweden', 'sweden.gif'),(3, 'Russian Federation', 'russia.gif'),(4, 'Finland', 'finland.gif'),
(5, 'Canada', 'canada.gif'),(6, 'France', 'france.gif'),(7, 'Germany', 'germany.gif'),
(8, 'China', 'china.gif'),(9, 'Italy', 'italy.gif'),(10, 'Denmark', 'denmark.gif'),
(11, 'Norway', 'norway.gif'),(12, 'United Kingdom', 'uk.gif'),(13, 'Ireland', 'ireland.gif'),
(14, 'Poland', 'poland.gif'),(15, 'Netherlands', 'netherlands.gif'),(16, 'Belgium', 'belgium.gif'),
(17, 'Japan', 'japan.gif'),(18, 'Brazil', 'brazil.gif'),(19, 'Argentina', 'argentina.gif'),
(20, 'Australia', 'australia.gif'),(21, 'New Zealand', 'newzealand.gif'),(23, 'Spain', 'spain.gif'),
(24, 'Portugal', 'portugal.gif'),(25, 'Mexico', 'mexico.gif'),(26, 'Singapore', 'singapore.gif'),
(29, 'South Africa', 'southafrica.gif'),(30, 'South Korea', 'southkorea.gif'),
(31, 'Jamaica', 'jamaica.gif'),(32, 'Luxembourg', 'luxembourg.gif'),(33, 'Hong Kong', 'hongkong.gif'),
(34, 'Belize', 'belize.gif'),(35, 'Algeria', 'algeria.gif'),(36, 'Angola', 'angola.gif'),
(37, 'Austria', 'austria.gif'),(38, 'Yugoslavia', 'yugoslavia.gif'),(39, 'Western Samoa', 'westernsamoa.gif'),
(40, 'Malaysia', 'malaysia.gif'),(41, 'Dominican Republic', 'dominicanrep.gif'),(42, 'Greece', 'greece.gif'),
(43, 'Guatemala', 'guatemala.gif'),(44, 'Israel', 'israel.gif'),(45, 'Pakistan', 'pakistan.gif'),
(46, 'Czech Republic', 'czechrep.gif'),(47, 'Serbia', 'serbia.gif'),(48, 'Seychelles', 'seychelles.gif'),
(49, 'Taiwan', 'taiwan.gif'),(50, 'Puerto Rico', 'puertorico.gif'),(51, 'Chile', 'chile.gif'),
(52, 'Cuba', 'cuba.gif'),(53, 'Congo', 'congo.gif'),(55, 'Turkey', 'turkey.gif'),
(56, 'Uzbekistan', 'uzbekistan.gif'),(57, 'Switzerland', 'switzerland.gif'),(58, 'Kiribati', 'kiribati.gif'),
(59, 'Philippines', 'philippines.gif'),(60, 'Burkina Faso', 'burkinafaso.gif'),(61, 'Nigeria', 'nigeria.gif'),
(62, 'Iceland', 'iceland.gif'),(63, 'Nauru', 'nauru.gif'),(64, 'Slovenia', 'slovenia.gif'),
(65, 'Albania', 'albania.gif'),(66, 'Turkmenistan', 'turkmenistan.gif'),
(67, 'Bosnia and Herzegovina', 'bosniaherzegovina.gif'),(68, 'Andorra', 'andorra.gif'),
(69, 'Lithuania', 'lithuania.gif'),(70, 'India', 'india.gif'),(71, 'Netherlands Antilles', 'nethantilles.gif'),
(72, 'Ukraine', 'ukraine.gif'),(73, 'Venezuela', 'venezuela.gif'),(74, 'Hungary', 'hungary.gif'),
(75, 'Romania', 'romania.gif'),(76, 'Vanuatu', 'vanuatu.gif'),(77, 'Vietnam', 'vietnam.gif'),
(78, 'Trinidad and Tobago', 'trinidadandtobago.gif'),(79, 'Honduras', 'honduras.gif'),
(80, 'Kyrgyzstan', 'kyrgyzstan.gif'),(81, 'Ecuador', 'ecuador.gif'),(82, 'Bahamas', 'bahamas.gif'),
(83, 'Peru', 'peru.gif'),(84, 'Cambodia', 'cambodia.gif'),(85, 'Barbados', 'barbados.gif'),
(86, 'Bangladesh', 'bangladesh.gif'),(87, 'Laos', 'laos.gif'),(88, 'Uruguay', 'uruguay.gif'),
(89, 'Antigua and Barbuda', 'antiguabarbuda.gif'),(90, 'Paraguay', 'paraguay.gif'),
(92, 'Union of Soviet Socialist', 'ussr.gif'),(93, 'Thailand', 'thailand.gif'),
(94, 'Senegal', 'senegal.gif'),(95, 'Togo', 'togo.gif'),(96, 'North Korea', 'northkorea.gif'),
(97, 'Croatia', 'croatia.gif'),(98, 'Estonia', 'estonia.gif'),(99, 'Colombia', 'colombia.gif'),
(100, 'Lebanon', 'lebanon.gif'),(101, 'Latvia', 'latvia.gif'),(102, 'Costa Rica', 'costarica.gif'),
(103, 'Egypt', 'egypt.gif'),(104, 'Bulgaria', 'bulgaria.gif'),(105, 'Isla de Muerte', 'jollyroger.gif'),
(112, 'Tunisia', 'tunisia.gif'),(114, 'Georgia', 'georgia.gif'),(117, 'Afghanistan', 'afghanistan.gif');

-- cron
INSERT IGNORE INTO `cron` (`cronid`, `nextrun`, `minutes`, `filename`, `description`, `loglevel`, `active`) VALUES
(1, 0, 1320, 'hourly_cleanups.php', 'This script performs various cleanup tasks once per hour.', 1, 1),
(18, 0, 2400, 'backupdb.php', 'DataBase Backup', 1, 1),
(19, 0, 1080, 'checktables.php', 'Check Tables', 1, 1),
(20, 0, 1200, 'threadviews.php', 'Thread Views', 1, 1),
(21, 0, 3600, 'optimizedb.php', 'OptiMize DB', 1, 1),
(22, 0, 3000, 'daily_cleanups.php', 'This script performs various cleanup tasks once per day', 1, 1),
(23, 0, 18000, 'usercleanup.php', 'Automatically expires bans, warnings and posting suspension and moderation times for users.', 1, 1),
(26, 0, 180, 'sendmailqueue.php', 'Sends the mail queue every minute.', 1, 1),
(30, 0, 1860, 'delayedmoderation.php', 'Automatically performs delayed moderation actions every 24 hours.', 1, 1),
(31, 0, 1200, 'torrentspromo.php', 'Automatically updates torrent promotions and expires old ones.', 1, 1),
(32, 0, 900, 'seedbonus.php', 'Automatically updates users seedbonus', 1, 1),
(33, 0, 1260, 'logcleanup.php', 'Automatically cleans up old log files.', 1, 1),
(34, 0, 3600 ,'weekly_cleanups.php','This script performs various cleanup tasks once per week', 1, 1);


-- spiders
INSERT IGNORE INTO `spiders` (`sid`, `name`, `theme`, `language`, `usergroup`, `useragent`, `lastvisit`) VALUES
(1, 'Google', 0, '', 0, 'Googlebot', 0),
(2, 'Bing', 0, '', 0, 'bingbot', 0),
(3, 'Alexa Internet', 0, '', 0, 'ia_archiver', 0),
(4, 'Ask.com', 0, '', 0, 'Teoma', 0),
(5, 'Baidu', 0, '', 0, 'Baiduspider', 0),
(6, 'Yandex', 0, '', 0, 'YandexBot', 0),
(7, 'Facebook', 0, '', 0, 'facebookexternalhit', 0),
(8, 'Twitter', 0, '', 0, 'Twitterbot', 0),
(9, 'Internet Archive', 0, '', 0, 'archive.org_bot', 0),
(10, 'Discord', 0, '', 0, 'Discordbot', 0),
(11, 'Applebot', 0, '', 0, 'Applebot', 0),
(12, 'CheckHost', 0, '', 0, 'CheckHost', 0),
(13, 'Pingdom', 0, '', 0, 'Pingdom.com_bot', 0),
(14, 'DuckDuckGo', 0, '', 0, 'DuckDuckBot', 0),
(15, 'UptimeRobot', 0, '', 0, 'UptimeRobot', 0);

-- smilies
INSERT IGNORE INTO `smilies` (`sid`, `stitle`, `stext`, `spath`, `sorder`) VALUES
(1,'alien',':alien:','alien.gif',1),(2,'angel',':angel:','angel.gif',1),(3,'angry',':angry:','angry.gif',1),
(4,'arrow',':arrow:','arrow.gif',1),(5,'arrow2',':arrow2:','arrow2.gif',1),(6,'blink',':blink:','blink.gif',1),
(7,'blush',':blush:','blush.gif',1),(8,'bow',':bow:','bow.gif',1),(9,'boxing',':boxing:','boxing.gif',1),
(10,'cake',':cake:','cake.gif',1),(11,'cap',':cap:','cap.gif',1),(12,'chef',':chef:','chef.gif',1),
(13,'cigar',':cigar:','cigar.gif',1),(14,'clap',':clap:','clap.gif',1),(15,'clap2',':clap2:','clap2.gif',1),
(16,'closedeyes',':closedeyes:','closedeyes.gif',1),(17,'clover',':clover:','clover.gif',1),
(18,'clown',':clown:','clown.gif',1),(19,'confused',':confused:','confused.gif',1),
(20,'cool1',':cool1:','cool1.gif',1),(21,'cool2',':cool2:','cool2.gif',1),(22,'cowboy',':cowboy:','cowboy.gif',1),
(23,'crazy',':crazy:','crazy.gif',1),(24,'crockett',':crockett:','crockett.gif',1),(25,'cry',':cry:','cry.gif',1),
(26,'cylon',':cylon:','cylon.gif',1),(27,'dawgie',':dawgie:','dawgie.gif',1),
(28,'detective',':detective:','detective.gif',1),(29,'devil',':devil:','devil.gif',1),
(30,'dumbells',':dumbells:','dumbells.gif',1),(31,'evil',':evil:','evil.gif',1),
(32,'evilmad',':evilmad:','evilmad.gif',1),(33,'evo',':evo:','evo.gif',1),(34,'excl',':excl:','excl.gif',1),
(35,'fez',':fez:','fez.gif',1),(36,'flowers',':flowers:','flowers.gif',1),(37,'fun',':fun:','fun.gif',1),
(38,'geek',':geek:','geek.gif',1),(39,'greedy',':greedy:','greedy.gif',1),(40,'grin',':D','grin.gif',1),
(41,'guns',':guns:','guns.gif',1),(42,'hannibal',':hannibal:','hannibal.gif',1),(43,'happy',':happy:','happy.gif',1),
(44,'happy2',':happy2:','happy2.gif',1),(45,'hmm',':hmm:','hmm.gif',1),(46,'hmmm',':hmmm:','hmmm.gif',1),
(47,'hooray',':hooray:','hooray.gif',1),(48,'huh',':huh:','huh.gif',1),(49,'icecream',':icecream:','icecream.gif',1),
(50,'idea',':idea:','idea.gif',1),(51,'ike',':ike:','ike.gif',1),(52,'indian',':indian:','indian.gif',1),
(53,'innocent',':innocent:','innocent.gif',1),(54,'jacko',':jacko:','jacko.gif',1),(55,'judge',':judge:','judge.gif',1),
(57,'king',':king:','king.gif',1),(58,'kiss',':kiss:','kiss.gif',1),(59,'kissing',':kissing:','kissing.gif',2),
(60,'kissing2',':kissing2:','kissing2.gif',2),(61,'laugh',':laugh:','laugh.gif',1),(62,'look',':look:','look.gif',1),
(63,'love',':love:','love.gif',1),(64,'lovers',':lovers:','lovers.gif',2),(65,'mama',':mama:','mama.gif',1),
(66,'mario',':mario:','mario.gif',1),(67,'medieval',':medieval:','medieval.gif',1),(68,'mml',':mml:','mml.gif',1),
(69,'music',':music:','music.gif',1),(70,'ninja',':ninja:','ninja.gif',1),(71,'no',':no:','no.gif',1),
(72,'noexpression',':|','noexpression.gif',1),(73,'nugget',':nugget:','nugget.gif',1),(74,'nuke',':nuke:','nuke.gif',1),
(75,'ohmy',':ohmy:','ohmy.gif',1),(76,'oldtimer',':oldtimer:','oldtimer.gif',1),(77,'osama',':osama:','osama.gif',1),
(78,'party',':party:','party.gif',1),(79,'pimp',':pimp:','pimp.gif',1),(80,'pirate',':pirate:','pirate.gif',1),
(81,'pirate2',':pirate2:','pirate2.gif',1),(82,'police',':police:','police.gif',1),(83,'pope',':pope:','pope.gif',1),
(84,'question',':question:','question.gif',1),(85,'rambo',':rambo:','rambo.gif',1),(86,'ras',':ras:','ras.gif',0),
(87,'rip',':rip:','rip.gif',2),(88,'rock',':rock:','rock.gif',1),(90,'rolleyes',':rolleyes:','rolleyes.gif',0),
(91,'sad',':(','sad.gif',0),(92,'saddam',':(dam','saddam.gif',1),(93,'santa',':santa:','santa.gif',1),
(94,'sheep',':sheep:','sheep.gif',1),(95,'shifty',':shifty:','shifty.gif',1),(96,'shit',':shit:','shit.gif',1),
(98,'shoot2',':shoot2:','shoot2.gif',2),(99,'shutup',':shutup:','shutup.gif',1),
(100,'shutup2',':shutup2:','shutup2.gif',1),(101,'sick',':sick:','sick.gif',0),(102,'slap',':slap:','slap.gif',1),
(103,'sleep',':sleep:','sleep.gif',0),(104,'sleeping',':sleeping:','sleeping.gif',1),(105,'sly',':sly:','sly.gif',1),
(106,'smart',':smart:','smart.gif',0),(107,'smartass',':smartass:','smartass.gif',0),
(108,'smile1',':)','smile1.gif',0),(109,'smile2',':smile2:','smile2.gif',0),(110,'smurf',':smurf:','smurf.gif',1),
(111,'snap',':snap:','snap.gif',1),(112,'sneaky',':sneaky:','sneaky.gif',0),(114,'spider',':spider:','spider.gif',2),
(115,'spidey',':spidey:','spidey.gif',1),(116,'tease',':tease:','tease.gif',1),
(117,'thankyou',':thankyou:','thankyou.gif',2),(118,'thumbsdown',':thumbsdown:','thumbsdown.gif',1),
(119,'thumbsup',':thumbsup:','thumbsup.gif',1),(120,'tongue',':P','tongue.gif',0),
(121,'unsure',':unsure:','unsure.gif',0),(122,'w00t',':w00t:','w00t.gif',0),(123,'wacko',':wacko:','wacko.gif',0),
(124,'wall',':wall:','wall.gif',1),(125,'wave',':wave:','wave.gif',0),(126,'wavecry',':wavecry:','wavecry.gif',1),
(127,'weakbench',':weakbench:','weakbench.gif',1),(128,'weep',':weep:','weep.gif',0),
(129,'weirdo',':weirdo:','weirdo.gif',0),(130,'whistle',':whistle:','whistle.gif',0),
(131,'wink',';)','wink.gif',0),(132,'wizard',':wizard:','wizard.gif',1),(133,'wolverine',':wolverine:','wolverine.gif',1),
(134,'wub',':wub:','wub.gif',1),(135,'yawn',':yawn:','yawn.gif',1),(136,'yes',':yes:','yes.gif',0),
(137,'yikes',':yikes:','yikes.gif',0),(138,'yucky',':yucky:','yucky.gif',0),(139,'zorro',':zorro:','zorro.gif',1),
(140,'zany',':zany:','zany-face.png',1),(141,'winking',':winking:','winking_face_with_tongue.gif',1),
(142,'hearteyes',':hearteyes:','smiling_face_with_heart_eyes.gif',1),(143,'yawning',':yawning:','yawning_face.gif',1),
(144,'unamused_face',':unamused_face:','unamused_face.gif',1),(145,'broken_heart',':brokenheart:','broken_heart.gif',1),
(147,'upsidedownface',':upsidedownface:','upside_down_face.gif',0),(148,'woozy',':woozy_face:','woozy_face.gif',0),
(149,'biking',':biking:','woman_biking.gif',0);

-- seedbonus_settings
INSERT IGNORE INTO `seedbonus_settings` (`id`, `setting_key`, `setting_value`, `setting_type`, `setting_group`, `description`) VALUES
(1,'enabled','yes','boolean','general','Enable/disable seedbonus system'),
(2,'base_bonus','2.5','float','general','Base bonus per hour'),
(3,'hour_cap','250','integer','general','Maximum bonus per hour per user'),
(4,'torrent_multiplier_type','penalty','string','general','Torrent count multiplier type'),
(5,'flat_multiplier','1','integer','general','Flat multiplier value'),
(6,'leech_none','1','integer','multipliers','Multiplier for torrents with 0 leechers'),
(7,'leech_few','1.2','float','multipliers','Multiplier for torrents with 1-2 leechers'),
(8,'leech_many','1.5','float','multipliers','Multiplier for torrents with 3+ leechers'),
(9,'size_small','0.8','float','multipliers','Multiplier for torrents < 0.5GB'),
(10,'size_medium','1','integer','multipliers','Multiplier for torrents < 2GB'),
(11,'size_large','1.2','float','multipliers','Multiplier for torrents < 8GB'),
(12,'size_xlarge','1.3','float','multipliers','Multiplier for torrents < 20GB'),
(13,'size_huge','1.5','float','multipliers','Multiplier for torrents >= 20GB'),
(14,'seeders_many','0.7','float','multipliers','Penalty multiplier for torrents with >100 seeders'),
(15,'seeders_medium','0.85','float','multipliers','Penalty multiplier for torrents with >50 seeders'),
(16,'age_old','1.2','float','multipliers','Bonus multiplier for torrents older than 180 days'),
(17,'age_medium','1.1','float','multipliers','Bonus multiplier for torrents older than 60 days'),
(18,'promo_free','0.3','float','multipliers','Additional bonus for Freeleech torrents'),
(19,'promo_silver','0.2','float','multipliers','Additional bonus for Silver torrents'),
(20,'promo_double','0.2','float','multipliers','Additional bonus for Double Upload torrents'),
(21,'cron_interval','15','integer','time','Cron interval in minutes'),
(22,'announce_interval','15','integer','time','Announce interval in minutes'),
(23,'history_days','1','integer','time','Activity history in days'),
(24,'enable_heuristic','on','string','time','Enable time seeding heuristic'),
(25,'heuristic_50','24','integer','heuristic','Assumed hours for 50+ torrents'),
(26,'heuristic_40','20','integer','heuristic','Assumed hours for 40+ torrents'),
(27,'heuristic_30','16','integer','heuristic','Assumed hours for 30+ torrents'),
(28,'heuristic_20','12','integer','heuristic','Assumed hours for 20+ torrents'),
(29,'heuristic_10','8','integer','heuristic','Assumed hours for 10+ torrents'),
(30,'heuristic_5','4','integer','heuristic','Assumed hours for 5+ torrents'),
(31,'heuristic_1','2','integer','heuristic','Assumed hours for 1-4 torrents'),
(32,'max_db_value','9999999.9','float','system','Maximum bonus value in database'),
(33,'batch_size','100','integer','system','Batch size for processing'),
(34,'exchange_ratio','0.01','float','system','Bonus exchange ratio'),
(35,'min_seedtime','72','integer','system','Minimum seeding time in hours'),
(36,'freeleech_cost','1000','integer','costs','Cost for Freeleech'),
(37,'invite_cost','5000','integer','costs','Cost for invite'),
(38,'upload_credit_cost','500','integer','costs','Cost for upload credit'),
(39,'double_upload_cost','10000','integer','costs','Cost for Double Upload status'),
(40,'vip_status_cost','20000','integer','costs','Cost for VIP status'),
(41,'other_status_cost','10000','integer','costs','Cost for other status'),
(42,'points_for_upload','50','integer','activity','Points for upload'),
(43,'points_for_forum_post','1','integer','activity','Points for forum post'),
(44,'points_for_topic','5','integer','activity','Points for topic'),
(45,'points_for_comment','2','integer','activity','Points for comment'),
(46,'points_per_week','100','integer','activity','Weekly bonus points');

-- staffpanel
INSERT IGNORE INTO `staffpanel` (`id`, `name`, `description`, `filename`, `usergroups`) VALUES
(1, 'adduser', 'Add New User', 'adduser.php', '[5],[6],[8]'),
(4, 'allagents', 'Show ALL Agents', 'allagents.php', '[5],[6],[8]'),
(5, 'amountbonus', 'Send Bonus Points', 'amountbonus.php', '[8],[8]'),
(6, 'announcements', 'Manage Announcements', 'announcements.php', '[6],[7],[8]'),
(8, 'bonuspoints', 'Manage Karma Point System', 'bonuspoints.php', '[6],[7],[8]'),
(9, 'category', 'Manage Tracker Categories', 'category.php', '[8],[6]'),
(10, 'changemail', 'Change Email', 'changemail.php', '[8],[8],[6]'),
(11, 'changeusername', 'Change Username', 'changeusername.php', '[8],[8],[6]'),
(13, 'cleartable', 'Clear SQL Tables', 'cleartable.php', '[8]'),
(14, 'country', 'Manage Countries', 'country.php', '[8],[6]'),
(18, 'docleanup', 'Run CleanUp', 'docleanup.php', '[8],[6]'),
(19, 'faqmanage', 'Manage FAQ', 'faqmanage.php', '[8],[6],[5]'),
(20, 'findnotconnectable', 'Show Not Connectable Users', 'findnotconnectable.php', '[8],[8],[6],[10],[5]'),
(21, 'freeleech', 'Manage Free-Leech', 'freeleech.php', '[5],[6],[8]'),
(24, 'ipsearch', 'Search IP', 'ipsearch.php', '[8],[6],[10],[5]'),
(26, 'log', 'Show Tracker Log', 'log.php', '[8],[6],[10],[5]'),
(27, 'massinvite', 'Send Mass Invite', 'massinvite.php', '[8],[6]'),
(28, 'massmail', 'Send Mass EMail', 'massmail.php', '[8],[6],[5]'),
(29, 'maxlogin', 'Show Failed Logins', 'maxlogin.php', '[8],[6]'),
(30, 'modrules', 'Manage Rules', 'modrules.php', '[8],[6],[5]'),
(31, 'mysql_overview', 'MYSQL Overview', 'mysql_overview.php', '[8]'),
(32, 'mysql_stats', 'MYSQL Stats', 'mysql_stats.php', '[8]'),
(33, 'news', 'Manage News', 'news.php', '[8],[6],[10],[5]'),
(34, 'ratio', 'Update Users Ratio', 'ratio.php', '[8],[6],[5]'),
(37, 'reports', 'Manage Reports', 'reports.php', '[8],[6],[10],[5]'),
(40, 'snatched_torrents', 'Show Snatched Torrents', 'snatched_torrents.php', '[8],[6],[10],[5]'),
(41, 'spam', 'Show User PMs', 'spam.php', '[8],[6],[10],[5]'),
(42, 'staffbox', 'Show Staff Messages', 'staffbox.php', '[8],[8],[6],[10],[5]'),
(43, 'staffmess', 'Send Mass PM', 'staffmess.php', '[8],[6],[10],[5]'),
(47, 'traceroute', 'Traceroute IP', 'traceroute.php', '[8],[6],[10],[5]'),
(49, 'uploadadd', 'Update Users Uploaded Amounts', 'uploadadd.php', '[8],[6]'),
(50, 'uploaders', 'Show Uploaders', 'uploaders.php', '[8],[8],[6],[10],[5]'),
(51, 'usersearch', 'User Search', 'usersearch.php', '[8],[6],[5]'),
(53, 'viewpeers', 'View Peers', 'viewpeers.php', '[8],[6],[10],[5]'),
(54, 'viewunbaniprequest', 'View UNBAN Requests', 'viewunbaniprequest.php', '[8],[6]'),
(55, 'warned', 'Show Warns', 'warned.php', '[5],[6],[8]'),
(56, 'inactiveusers', 'Inactive Users Management', 'inactiveusers.php', '[8],[6],[5]'),
(62, 'delundeletedtorrents', 'Delete Undeleted Torrent Files', 'delundeletedtorrents.php', '[8],[6],[5]'),
(63, 'latest_comments', 'Show Latest Comments', 'latest_comments.php', '[5],[6],[8]'),
(64, 'fixhash', 'Fix Torrents (info_hash)', 'fixhash.php', '[8]'),
(66, 'serverinfo', 'Display Server Info', 'serverinfo.php', '[8],[6]'),
(67, 'cheat_attempts', 'Manage Cheat Attempts!', 'cheat_attempts.php', '[5],[6],[8]'),
(68, 'announce_actions', 'Possible cheat attempts on announce', 'announce_actions.php', '[6],[7],[8]'),
(69, 'tweak_tracker', 'Tweak Your Tracker', 'tweak_tracker.php', '[8]'),
(74, 'passkeysearch', 'Search Passkey', 'passkeysearch.php', '[8],[8],[6],[10],[5]'),
(75, 'iptocountry', 'IP to Country', 'iptocountry.php', '[8],[6],[10],[5]'),
(77, 'sendmail', 'Send Email to User', 'sendmail.php', '[8],[8],[6],[10],[5]'),
(80, 'manage_torrents', 'Manage Torrents', 'manage_torrents.php', '[8],[6],[5]'),
(81, 'mass_reseed', 'Mass Reseed Request', 'mass_reseed.php', '[5],[6],[8]'),
(82, 'detect_cheaters', 'Detect Cheaters', 'detect_cheaters.php', '[5],[6],[8]'),
(83, 'doubleupload', 'Manage Double Upload', 'doubleupload.php', '[8],[6],[10]'),
(84, 'manage_vip', 'Manage VIP Accounts', 'manage_vip.php', '[8],[6],[10],[5]'),
(85, 'hit_and_run', 'Detect Hit & Run', 'hit_and_run.php', '[5],[6],[8]'),
(86, 'removeadd', 'Remove User Upload Amounts', 'removeadd.php', '[8],[6],[10],[5]'),
(88, 'manage_avatars', 'Manage User Avatars', 'manage_avatars.php', '[5],[6],[8]'),
(94, 'downloadadd', 'Update Users Downloaded Amounts', 'downloadadd.php', '[8],[6],[10],[5]'),
(95, 'logmails', 'Mails Log', 'logmails.php', '[8],[6],[10],[5]'),
(96, 'logmailserror', 'System Email Log', 'logmailserror.php', '[8],[6],[10],[5]'),
(98, 'backupdb', 'Manage Database', 'backupdb.php', '[8],[6],[5]'),
(99, 'cache', 'Cache Manager', 'cache.php', '[8],[6],[5]'),
(100, 'recount_rebuild', 'Recount & Rebuild', 'recount_rebuild.php', '[8],[6],[5]'),
(101, 'awaiting_activation', 'Manage Awaiting Activation', 'awaiting_activation.php', '[8],[6],[5]'),
(102, 'management', 'Forum Management', 'management.php', '[8],[6],[5]'),
(103, 'groups', 'Manage User Groups', 'groups.php', '[8]'),
(104, 'banning', 'Banned Accounts', 'banning.php', '[6],[7],[8]'),
(105, 'attachments', 'Manage Attachments', 'attachments.php', '[5],[6],[8]'),
(106, 'attachment_types', 'Attachment Types', 'attachment_types.php', '[5],[6],[8]'),
(107, 'view_error_logs', 'View Error Logs', 'view_error_logs.php', '[5],[6],[8]'),
(108, 'csseditor', 'Manage CSS Styles', 'csseditor.php', '[5],[6],[8]'),
(109, 'smilies', 'Manage Smiles', 'smilies.php', '[5],[6],[8]'),
(111, 'torrentstats', 'Torrent Stats', 'torrentstats.php', '[5],[6],[8]'),
(112, 'manage_screenshots', 'Manage Screenshots', 'manage_screenshots.php', '[6],[7],[8]'),
(113, 'manage_uploads', 'Manage Uploaded Images', 'manage_uploads.php', '[6],[7],[8]'),
(114, 'execute_sql_query', 'Run SQL Query Tool', 'execute_sql_query.php', '[8]'),
(115, 'cronjobs', 'Manage Cronjobs', 'cronjobs.php', '[8]'),
(116, 'torrents_promo', 'Torrent Promotional', 'torrents_promo.php', '[5],[6],[8]'),
(117, 'batch_upload', 'Multi Torrents Uploads', 'batch_upload.php', '[5],[6],[8]'),
(118, 'seedbonus_settings', 'configure seedbonus', 'seedbonus_settings.php', '[8]'),
(119, 'manage_invites', 'Manage Invites', 'manage_invites.php', '[8]'),
(120, 'phpeditor', 'Edit php files', 'phpeditor.php', '[8]'),
(121, 'announcements_forum', 'Manage Forum Announcements', 'announcements_forum.php', '[6],[7],[8]'),
(122, 'modcp', 'Threads and Posts Awaiting Moderation', 'modcp.php', '[6],[7],[8]'),
(123, 'manage_polls', 'Manage Polls', 'manage_polls.php', '[6],[7],[8]');